### ISSUE TITLE
申请啦

### ISSUE THREAD

**Issue by feiyou233** [volfclub/travellings#1]

**Comment by volfclub** [comment]
网站不符合要求

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
