### ISSUE TITLE
Leo’s Blog 申请加入

### ISSUE THREAD

**Issue by LeoCreate** [volfclub/travellings#100]
## 网站名称 
Leo's Blog

## 网站链接 
https://www.isolitude.cn/

## 徽标位置 
全局右侧边栏，手机版底部
全局左边栏

## 推荐理由 
发现生活的点点滴滴，美好趣事。

**Comment by volfclub** [comment]
已收录

**Comment by volfclub** [comment]
你的网站 520 报错了

**Comment by LeoCreate** [comment]
> 你的网站 520 报错了

已修复
