### ISSUE TITLE
山葵酱 Wasabi

### ISSUE THREAD

**Issue by 213wasabi** [volfclub/travellings#102]

**Comment by volfclub** [comment]
建议在侧栏或其他打开网页就能直接看到的位置填一个外链

**Comment by 213wasabi** [comment]
换到侧栏啦，再看看~
https://wasabi.fun/
![image](https://user-images.githubusercontent.com/42235062/80272476-673aaa80-86fc-11ea-95ba-01e3fa2ef79f.png)

**Comment by volfclub** [comment]
嗨，位置可以靠上些吗？建议打开网页后就能看到

**Comment by 213wasabi** [comment]
好👌

逊狼 <notifications@github.com>于2020年5月1日 周五16:53写道：

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
