### ISSUE TITLE
魏·美文网 申请收入

### ISSUE THREAD

**Issue by boxcheese** [volfclub/travellings#103]
## 网站名称
魏·美文网
## 网站链接
https://xiaowei.china97.cn
## 徽标位置
底拦和侧滑栏
 （Travellings）（这个要遵循语法，别人都是可以看见的，请见谅，谢谢）
## 推荐理由
美文了解人们的心情与感受，每日美文从写作开始！

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
