### ISSUE TITLE
美文网申请收入

### ISSUE THREAD

**Issue by boxcheese** [volfclub/travellings#106]
## 网站名称
魏·美文网 
## 网站链接
https://xiaowei.china97.cn/
## 徽标位置
侧滑栏和底拦
（置顶文章第二个已经很明显了，进去就可以立马看到）
## 推荐理由
无论网站是什么类型，做了就一定要坚持，我每天坚持为大家更新文章，这可能就是我的坚持，不过我知道本站可能不符合要求加入开往，我一天十几二十的流量，也希望让更多人一起来学习，来阅读这些小短句，不知能否通过！
##特殊情况
本人已经返校，我是初二的一名学生，学校处于半失联状态，所以看不到文件，所以能不能包容一下，收入一下网站，非常感谢！如果不行的话那就算了吧……等我回来再次申请✘

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
