### ISSUE TITLE
Smilear's Blog请求收录

### ISSUE THREAD

**Issue by L-20021213** [volfclub/travellings#107]
## 网站名称
Smilear's Blog
## 网站链接
http://smilear.cn/
## 徽标位置
导航栏
## 推荐理由
想让跟多人看到我的博客（如果打不开就是缓存，已经提交好多次了，哭了）

**Comment by volfclub** [comment]
> 导致网站被拦截的原因可能如下：
原因一：该网站已备案，但尚未提交白名单，登录服务提供商控制台-备案管理处提交白名单后即可正常访问；
原因二：根据工信部相关法规，该网站尚未进行备案，请登录服务提供商控制台-备案管理处提交备案；
本页面为默认提示页面，如网站存在以上问题，可联系服务提供商处理。
谢谢合作！

**Comment by volfclub** [comment]
抱歉，我真的打不开……

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
