### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by chingxiang** [volfclub/travellings#108]
## 网站名称
花开陌上
## 网站链接
https://moshanghua.net/
## 徽标位置
首页/底部
## 推荐理由
谁人踏花拾锦年，陌上花开缓缓归！

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
