### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by bukezhi** [volfclub/travellings#109]
## 网站名称
有次博客
## 网站链接
https://you.ci/
## 徽标位置
底部
## 推荐理由
开往可以打开另外一扇大门，很喜欢，会一直放下去，希望您也可以坚持好这个项目，这个好作品，^_^

**Comment by volfclub** [comment]
顶栏导航来一个开往的外链吧。
顺便一说，现在的浏览器非https地址栏会有警告，也不是很好看

**Comment by bukezhi** [comment]
> 顶栏导航来一个开往的外链吧。
> 顺便一说，现在的浏览器非https地址栏会有警告，也不是很好看

已经顶部添加，^_^ [有次博客](https://you.ci/)

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
