### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by D-DeepWave** [volfclub/travellings#110]
## 网站名称
德令哈
## 网站链接
https://www.deepwave.top/
## 徽标位置
首页/底部
## 推荐理由
我不祝你一帆风顺，我祝你乘风破浪

**Comment by D-DeepWave** [comment]
更新，徽标移至左侧导航栏中

**Comment by D-DeepWave** [comment]
为什么上次审核单独跳过了我的。。。

**Comment by volfclub** [comment]
已收录，有可能眼花看回复的单双数漏了

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
