### ISSUE TITLE
申请加入，青行三

### ISSUE THREAD

**Issue by jiehua1995** [volfclub/travellings#112]
## 网站名称
青行三の个人博客
## 网站链接
https://blog.jiehua1995.xyz
## 徽标位置
顶部导航栏“Travelling”
## 推荐理由
个人博客，会更新一些Hexo相关的使用经验和文学类写作。

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
