### ISSUE TITLE
申请加入开往！

### ISSUE THREAD

**Issue by sabaizzz** [volfclub/travellings#113]
## 网站名称
编程与诗
## 网站链接
https://www.tjzzz.com/
## 徽标位置
侧边栏
## 推荐理由
一位主播与程序员的奇妙组合，你不会失望的。

**Comment by volfclub** [comment]
能不能把徽标放在一个打开网页能直接看到的位置？

**Comment by sabaizzz** [comment]
这已经算是最显眼的地方啦，要不我放到foot里和又拍云并肩？也可以



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "逊狼"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 晚上7:55
收件人: "volfclub/travellings"<travellings@noreply.github.com&gt;; 
抄送: "飒白"<sabai@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [volfclub/travellings] 申请加入开往！ (#113)





 
能不能把徽标放在一个打开网页能直接看到的位置？

**Comment by sabaizzz** [comment]
![](img.tjzzz.com/img/20200423201328.png)
放这也行

**Comment by sabaizzz** [comment]
[示例图片](img.tjzzz.com/img/20200423201328.png)

**Comment by volfclub** [comment]
抱歉，并没能找到徽标。放在打开网页能看到的位置就行
