### ISSUE TITLE
Ying 申请收录

### ISSUE THREAD

**Issue by luvying** [volfclub/travellings#114]
## 网站名称
Ying
## 网站链接
https://yingserver.cn/
## 徽标位置
底部
## 推荐理由
希望能够更多人看到~

**Comment by volfclub** [comment]
建议在顶部导航放一个开往的外链，打开网页就能看到

**Comment by cxying** [comment]
> 建议在顶部导航放一个开往的外链，打开网页就能看到

已添加

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
