### ISSUE TITLE
收录申请 >>> lipk.org   - 来人，快把这妖怪收了！

### ISSUE THREAD

**Issue by zsdycs** [volfclub/travellings#117]
## 网站名称
执手对影成双-个人网站

## 网站链接
[lipk.org](https://lipk.org)

## 徽标位置
底部图标

## 推荐理由
1. 源于 GitHub pages 稳定。
2. CDN && DNS 来自 [CloudFlare](https://cloudflare.com) 。

**Comment by volfclub** [comment]
已收录

**Comment by zsdycs** [comment]
已修改

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by zsdycs** [comment]
[已修改](https://github.com/zsdycs/lipk.org/commit/5124e8496062e37cf949283ecf59f19a420adcea)
