### ISSUE TITLE
皮毛技术君申请收录

### ISSUE THREAD

**Issue by dyt5AAUI** [volfclub/travellings#122]
## 网站名称
皮毛技术君
## 网站链接
https://www.whoit.top/
## 徽标位置
右侧链接
![image](https://user-images.githubusercontent.com/26762239/80548901-6e103880-89ee-11ea-854f-6bdd5f21628d.png)

## 推荐理由
希望参与这个项目。

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
