### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by takuron** [volfclub/travellings#126]
## 网站名称

Passer

## 网站链接

https://takuron.top/

## 徽标位置

未使用徽标，改用顶栏TRAVELLING按钮

## 推荐理由

不务正业大学生的技术日常

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by takuron** [comment]
> 您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：
> 
> gif动图：https://www.travellings.cn/assets/logo.gif svg：https://www.travellings.cn/assets/logo.svg
> 
> 请您及时更换相关地址，谢谢配合。

您好，已经修改
