### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by IceFire-X** [volfclub/travellings#127]
## 网站名称
今今今生
## 网站链接
https://noheart.cn
## 徽标位置
https://icefiredb-1300435688.piccd.myqcloud.com/betsy/mylife_1578304645239.jpg
## 推荐理由
医不自医，人不渡己

**Comment by IceFire-X** [comment]
上边图表限制了可以改成这个：

https://noheart.cn/upload/mylife.jpg

**Comment by volfclub** [comment]
顶部导航放一个开往的外链吧

**Comment by IceFire-X** [comment]
页脚有放

**Comment by IceFire-X** [comment]
还没添加我嘛 铁子

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
