### ISSUE TITLE
跳转链接忽视来源

### ISSUE THREAD

**Issue by uniartisan** [volfclub/travellings#13]
现在的是手工录入并且随机链表跳转。
希望可以在有这个链接的来源网站点击后跳转时能在列表忽视来源网站。与此同时能在远程服务器记录跳转的来源链接（后期可以自动化录入）
其次，移动宽带ping这几个镜像站丢包率都很高，中午到了50%，希望可以有国内的镜像站或者CDN(CF,腾讯都有免费CDN)

**Comment by volfclub** [comment]
如果你擅长代码，可以 pull requests。比较抱歉的是我并不精通代码。
人工审核目前还是有必要的，自动收录可能导致被滥用的风险。
可以提供国内的CDN，但考虑到服务的长期运行，优先推荐了海外免费的镜像服务。

**Comment by uniartisan** [comment]
新增跳转忽视来源。 
自动收录需要服务器php配合，方案考虑以访问第三方页面记录来源网址。
**大大小小的孤岛散落在浩瀚烟海，来往就像是一颗颗星球之间的快速列车，随机的跳向下一站。**

**Comment by uniartisan** [comment]
Updated

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
