### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by MoeSakura233** [volfclub/travellings#130]
## 网站名称
Sakura's Blog
## 网站链接
https://iMagicSakura.github.io
## 徽标位置
侧边栏*
## 推荐理由
留下在人间的点滴记忆...
##注
本站已更换 正在重新搭建...

**Comment by volfclub** [comment]
- 文章有些少，建议篇以上再来申请下
- 能不能把开往的外链或徽标放在打开网页能直接看到的地方呢

**Comment by iMagicSakura** [comment]
目前暂时无法访问...

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
