### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by Musenxi** [volfclub/travellings#131]
## 网站名称
沐森西の博客
## 网站链接
https://dlizi.com:555/
## 徽标位置
顶部/底部
## 推荐理由
是微甜的呀

**Comment by volfclub** [comment]
已收录

**Comment by Musenxi** [comment]
原沐森西の博客现因改版先申请退出travelling，麻烦维护一下 谢谢。

**Comment by volfclub** [comment]
收导，感谢反馈

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
