### ISSUE TITLE
申请恢复收录

### ISSUE THREAD

**Issue by moefishtang** [volfclub/travellings#132]
## 网站名称
摸鱼堂
## 网站链接
moefishtang.xyz
## 徽标位置
页脚以及右侧侧栏，左侧侧栏，友链界面
## 推荐理由
之前因为服务器迁移原因临时关站，现在希望能够恢复。抱歉。

**Comment by volfclub** [comment]
好的

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
