### ISSUE TITLE
申请换链

### ISSUE THREAD

**Issue by Kagurain** [volfclub/travellings#137]
自说自话原域名 rua.ink现已更换至：blog.vn40.cn 原域名将在hstspreload list注销过后永久301至blog.vn40.cn

**Comment by volfclub** [comment]
您的博客似乎下线了？

**Comment by volfclub** [comment]
已下线

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
