### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by jalenchuh** [volfclub/travellings#138]
## 网站名称

Royce 的小窝

## 网站链接

https://royce2003.top/

## 徽标位置

顶栏和友链页（友链页因图片比例问题，用了自己的图片）
![image](https://user-images.githubusercontent.com/57910033/81044357-ca8bc000-8ee6-11ea-8d66-59835ef6f0eb.png)

## 推荐理由

个人博客，更新些 OI / 科技类内容

**Comment by MHuiG** [comment]
啊哈 😆

**Comment by volfclub** [comment]
已收录
