### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by ArchyMoe** [volfclub/travellings#139]
## 网站名称
UserUnknownX的小站
## 网站链接
https://userunknownx.github.io/
## 徽标位置
底部+侧边栏

用的是githubpage >_<
因为最近比较忙没时间看域名
因为能跳转就先放这个啦qwq

**Comment by UserUnknownX** [comment]
目前正在转hexo，博文还没有倒过去，得先等等

**Comment by volfclub** [comment]
建议搬运后再申请一次？
有个建议，静态博客可以解析个域名给zeit试试，国内访问速度还行

**Comment by UserUnknownX** [comment]
> 建议搬运后再申请一次？
> 有个建议，静态博客可以解析个域名给zeit试试，国内访问速度还行

已经搬运XD

感谢您的建议(事实上有域名了但正在想怎么用DNS，添加了zeit

换好了博客底部连接准备晚点加，侧边栏加好了的QwQ

**Comment by volfclub** [comment]
已收录
顺便一说，你百度统计的图糊了。百度统计可不放图了。

**Comment by UserUnknownX** [comment]
> 已收录
> 顺便一说，你百度统计的图糊了。百度统计可不放图了。

谢谢

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/ee77e8b8-52e8-451c-b46a-8a672aef01c9)

![Image](https://github.com/user-attachments/assets/09985b0f-ea4a-4041-9b1b-bedd690d6579)

![Image](https://github.com/user-attachments/assets/bf2f81ad-8edf-4eb6-a58d-ae456e334c2b)

确认过期，已移除，感谢支持，欢迎重新申请！
