### ISSUE TITLE
土豆和豌豆

### ISSUE THREAD

**Issue by Lulululx** [volfclub/travellings#140]

**Comment by Nothinglx** [comment]
是在左侧底部

**Comment by volfclub** [comment]
建议放在左侧栏一个外链，让人打开就能看到

**Comment by Nothinglx** [comment]
> 
> 
> 建议放在左侧栏一个外链，让人打开就能看到

好的  现在已经更改了-

**Comment by volfclub** [comment]
已收录

**Comment by Lulululx** [comment]
因为一些个人原因，网站更换
网站名称 陆碌路的小窝
网站链接 https://www.llululu.com
徽标位置 左侧边栏
推荐理由 分享自己的记录，学习以及感悟
