### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by fuzui** [volfclub/travellings#145]
## 网站名称
Geek Era
## 网站链接
https://www.geekera.cn
## 徽标位置
网页底部插入的徽标(顶部菜单栏Travelling)
## 推荐理由
喜欢分享，希望会结交更多的旁友！

**Comment by volfclub** [comment]
已收录

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已不支持SSL，现已将您移除，如需加入开往，可再次按照流程申请，再次申请可以@管理员快速审核。 @fuzui
