### ISSUE TITLE
Looni's blog

### ISSUE THREAD

**Issue by looniink** [volfclub/travellings#146]
## 网站名称
looni
## 网站链接
https://looni.ink/
## 徽标位置
底部
## 推荐理由
分享一些生活与技术，想和更多的小伙伴一起玩耍吖

**Comment by volfclub** [comment]
请在顶部导航加一个开往的外链

**Comment by looniink** [comment]
顶部已添加

**Comment by volfclub** [comment]
外链需要打开网页直接看到的
