### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by ccquan** [volfclub/travellings#147]
## 网站名称
Guang's blog

## 网站链接
[https://code016.com/](https://code016.com/)

## 徽标位置
网站底部，版权那里

## 推荐理由
seo，提高收录，分享文章

**Comment by volfclub** [comment]
建议侧栏也加入一个外链

**Comment by ccquan** [comment]
> 建议侧栏也加入一个外链

已经添加了

**Comment by volfclub** [comment]
已收录

**Comment by ccquan** [comment]
ok了

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
