### ISSUE TITLE
tabris的遥远星系

### ISSUE THREAD

**Issue by tabris-trees** [volfclub/travellings#154]
## 网站名称
tabris的遥远星系
## 网站链接
https://www.tabirstrees.top
## 徽标位置
底栏
## 推荐理由
分享一些生活和社会的看法，数学/物理/天文/地质科普，提升生活质量的小技巧/资源

**Comment by volfclub** [comment]
顶部导航给一个开往的外链吧

**Comment by essesy** [comment]
OK了
![图片](https://user-images.githubusercontent.com/39879580/82308382-495b1f80-99f4-11ea-8cae-5d8e052e7eac.png)

**Comment by volfclub** [comment]
已收录
