### ISSUE TITLE
三路清风

### ISSUE THREAD

**Issue by uu7788oo** [volfclub/travellings#157]
## 网站名称
三路清风
## 网站链接
https://www.yansanlu.com
## 徽标位置
底部
## 推荐理由
分享生活看法经验，小技巧资源等

**Comment by volfclub** [comment]
- 你的文章有些少，要不在写写？
- 建议将开往的外链放在左侧的导航

**Comment by uu7788oo** [comment]
> * 你的文章有些少,要不在写写？
> * 建议将开往的外链放在左侧的导航

嗯又写了几篇，还有“开往”功能添加到了，左侧导航菜单。

**Comment by volfclub** [comment]
已收录
