### ISSUE TITLE
螓首蛾眉

### ISSUE THREAD

**Issue by jsun969** [volfclub/travellings#158]
## 网站名称
螓首蛾眉
## 网站链接
https://myheod.cn
## 徽标位置
底部footer
## 推荐理由
个人博客 坚持技术分享讨论

**Comment by volfclub** [comment]
内容有些少，要不再写写看？

**Comment by jsun969** [comment]
啊这..最近忙中考不怎么写 七月以后会更新更多文章的..

**Comment by volfclub** [comment]
好的，建议到时再来申请一次

**Comment by jsun969** [comment]
不好意思，之前在主页隐藏了一些文章，现已全部显示，共计9篇文章，4条状态，麻烦收录

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
