### ISSUE TITLE
房东的猫 Bolg

### ISSUE THREAD

**Issue by flag-mac** [volfclub/travellings#159]
## 网站名称
房东的猫 Bolg
## 网站链接
https://www.fddmao.com/
## 徽标位置
http://image-access1.test.upcdn.net/2020/05/17/05e02dcd15ebe.jpeg
## 推荐理由
站在路人的肩膀上，怎么会知道自己的渺小。

**Comment by volfclub** [comment]
- 你的文章有些少，要不在写写？
- 建议将开往的外链放在左侧的导航

**Comment by Git-Angel** [comment]
邮件我已收到

1. 我会改到左边
2. 本来之前整好了 文章发挺多，中途魔改了一下 改坏了就重整了. 我会持续发的.
3. 收录了吧，谢谢了！


发自我的iPhone

**Comment by volfclub** [comment]
好，我会过几天再来审核一次

**Comment by volfclub** [comment]
已收录
