### ISSUE TITLE
烟雨故人归

### ISSUE THREAD

**Issue by BoostQ** [volfclub/travellings#161]
## 网站名称
烟雨故人归
## 网站链接
https://wency.site/
## 徽标位置
<img width="308" alt="屏幕快照 2020-05-17 上午10 46 48" src="https://user-images.githubusercontent.com/59366528/82134589-bbccd380-982b-11ea-9e1d-402af9f6ddc2.png">
侧栏联系方式处

##  推荐理由
个人博客，知识分享

**Comment by volfclub** [comment]
建议在网站底部也发一个外链

**Comment by Matlab-designer** [comment]
好的ヾ ^_^♪，正在修改中，预计明后天上线

**Comment by volfclub** [comment]
你的博客是不是改版了？目前内容有些少，再写写？
