### ISSUE TITLE
七米蓝网站的名字

### ISSUE THREAD

**Issue by ChirmyRam** [volfclub/travellings#162]
## 网站名称
七米蓝
## 网站链接
https://www.chirmyram.top/
## 徽标位置
顶部导航栏右侧及底部
https://s1.ax1x.com/2020/05/19/Y4mgZ6.jpg
https://s1.ax1x.com/2020/05/19/Y4m6qx.jpg
## 推荐理由
倾向写长文章，数量不多但精。

**Comment by volfclub** [comment]
一般建议有8篇以上内容时再来申请一次

**Comment by ChirmyRam** [comment]
> 一般建议有8篇以上内容时再来申请一次

已加入文章，目前有9篇文章，请求通过，非常感谢。

**Comment by volfclub** [comment]
文章似乎都是在同一天更新的，您会保持持续更新吗

**Comment by ChirmyRam** [comment]
> 文章似乎都是在同一天更新的，您会保持持续更新吗

如之前所说我是倾向于写长文章且反复修改同一篇文章，文章内容会保持更新。我建博客的原因就是因为没几个社交平台发文章支持反复修改，而我自己建博客可以实现不限次数的修改。
比如我的《Edge使用文档》自发布以来已经修改了上百次了，可以在文章末尾看到最近修改时间，大约一周一次，保持与微软官方更新进度一致，总计一万一千余字，如果把它拆分足以水十篇。
我比较看重文章内容的更新而不是数量，《Edge使用文档》和《Typecho搭建参考资料》是更新频率较快的两篇。
已等候您的回复多时，感谢回复。

**Comment by volfclub** [comment]
已收录

**Comment by ChirmyRam** [comment]
@volfclub 已更新至新的链接。

**Comment by ChirmyRam** [comment]
@vicevolf 已更新至新的链接。
