### ISSUE TITLE
Guyi’s Blog - 申请收录

### ISSUE THREAD

**Issue by Guyi888** [volfclub/travellings#164]
## emmm觉得这是一个不错的项目，然后，想提高自己网站的SEO并认识更多的小伙伴！！！
请求大佬大大通过审核！

**Comment by volfclub** [comment]
请将星球改为开往

**Comment by Guyi888** [comment]
> 摧毁星球改造开往

已修改

**Comment by Guyi888** [comment]
> > 摧毁星球改造开往
> 
> 已修改

**Comment by Guyi888** [comment]
emmmmmmmm

**Comment by volfclub** [comment]
已收录

**Comment by Guyi888** [comment]
谢谢~~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"逊狼"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月18日(星期四) 上午10:50
收件人:&nbsp;"volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送:&nbsp;"4710155"<4710155@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [volfclub/travellings] Guyi’s Blog - 申请收录 (#164)





 
已收录

**Comment by Guyi888** [comment]
已修改指向的域名及素材

**Comment by volfclub** [comment]
好的

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
