### ISSUE TITLE
九汐 收录申请

### ISSUE THREAD

**Issue by Freeaes** [volfclub/travellings#167]
## 网站名称
九汐
## 网站链接
https://blog.lu-sky.com
## 徽标位置
顶部
## 推荐理由
个人博客 技术分享 信息技术

**Comment by volfclub** [comment]
![image](https://user-images.githubusercontent.com/47265026/82730614-a1b35980-9d33-11ea-9596-d81d13bf0f35.png)
您网站的部分图片在国内似乎无法正常加载 😥

**Comment by Lusky-Git** [comment]
> ![圖片](https://user-images.githubusercontent.com/47265026/82730614-a1b35980-9d33-11ea-9596-d81d13bf0f35.png)
> 您網站的部分圖片在國內似乎無法正常加載 😥

**Comment by Lusky-Git** [comment]
已修复上述问题

**Comment by volfclub** [comment]
已收录
