### ISSUE TITLE
服务猿 申请收录

### ISSUE THREAD

**Issue by ishells** [volfclub/travellings#168]
## 网站名称
------
服务猿's 学习笔记

## 网站链接
------
https://www.ishells.cn

## 徽标位置
------
徽标网页底部，外链在顶部导航

## 推荐理由
个人运维学习之路学习笔记，会发一些体系的学习经验与故障排除过程与经验等文章，欢迎交流

**Comment by volfclub** [comment]
已收录

**Comment by ishells** [comment]
done

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已移除开往链接，现已将您移除，如需加入开往，可再次按照流程申请。 @ishells
