### ISSUE TITLE
尼采般地抒情

### ISSUE THREAD

**Issue by wztlink1013** [volfclub/travellings#169]
## 网站名称
尼采般地抒情
## 网站链接
https://www.wztlink1013.com/
## 徽标位置
- 顶部导航栏    
- 底部控件

![](https://cdn.jsdelivr.net/gh/wztlink1013/figure/blogarticle57/Snipaste_2020-05-22_00-58-16.png)

![](https://cdn.jsdelivr.net/gh/wztlink1013/figure/blogarticle57/Snipaste_2020-05-22_00-58-37.png)
## 推荐理由
惊鸿一面却也是缘分、

**Comment by volfclub** [comment]
已收录

**Comment by wztlink1013** [comment]
网站近期在自写代码重构，网站完善之后，会加上Travellings图标的

**Comment by volfclub** [comment]
了解
