### ISSUE TITLE
杜老师说

### ISSUE THREAD

**Issue by penndu** [volfclub/travellings#173]
## 网站名称
杜老师说
## 网站链接
https://dusays.com
## 徽标位置
导航文字，页脚配图
## 推荐理由
技术分享

**Comment by volfclub** [comment]
未发现开往的外链

**Comment by penndu** [comment]
你好，在页尾处！

**Comment by volfclub** [comment]
![image](https://user-images.githubusercontent.com/47265026/85023079-d2f23e80-b1a6-11ea-89e2-d989f61fe71f.png)
没找到。以及建议放在顶栏或侧栏导航等可以直接看到的地方

**Comment by penndu** [comment]
![Snipaste_2020-06-18_21-06-17.jpg](https://7bu.top/2020/06/18/1bcdd3cc8aec8.jpg)

**Comment by volfclub** [comment]
建议放在顶栏或侧栏导航等可以直接看到的地方

**Comment by volfclub** [comment]
嗨，再提醒一次，您的网站目前还没有收录，建议在顶部导航放一个开往的外链，打开网页就可看到

**Comment by penndu** [comment]
已经添加！

**Comment by volfclub** [comment]
已收录

**Comment by penndu** [comment]
> 【💥重要！】 抱歉 @penndu，由于不可抗力（ https://www.vercel-status.com/incidents/r758bhbklgfd ）导致 Travelling 在国内访问变得“艰难”，我们不得不放弃 Vercel 。
> 为确保后续的顺畅访问，请尽快将您网站 Travelling 指向的域名（包括图片素材），从【 https://travellings.now.sh 】更新为【 https://travellings.link 】。我们也会进行重定向处理，谢谢。
> 
> a. 如需任何帮助，请直接此回复 issue，并查看已更新的 Readme。
> b. 如已完成修改，可点击【Close issue】按钮关闭此 issue （如未收录请勿关闭）。

好的，我会尽快修改链接。另外这边有闲置服务器，可以提供访问支持！
