### ISSUE TITLE
静かな森

### ISSUE THREAD

**Issue by Innei** [volfclub/travellings#174]
## 网站名称
静かな森
## 网站链接
https://innei.ren/
## 徽标位置
footer
## 推荐理由
 生活&编程

**Comment by volfclub** [comment]
网站在国内打开有些困难，建议优化

**Comment by Innei** [comment]
还好吧，我已经把所有资源放到 jsdelivr 上了

**Comment by volfclub** [comment]
看了下，可能是因为主机在DO国内访问不稳定的原因
已收录

**Comment by volfclub** [comment]
忘记说了，顶部导航也要放一个开往的外链。用户打开可以直接看到

**Comment by Innei** [comment]
已加，请刷新缓存查看

**Comment by volfclub** [comment]
已收录

**Comment by Innei** [comment]
已换

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已移除开往链接，现已将您移除，如需加入开往，可再次按照流程申请。 @Innei
