### ISSUE TITLE
一觉睡到小时候

### ISSUE THREAD

**Issue by coder-lida** [volfclub/travellings#177]
## 网站名称
一觉睡到小时候
## 网站链接
https://likeyou.cool/
## 推荐理由
java 前端

**Comment by volfclub** [comment]
未发现开往的链接

**Comment by coder-lida** [comment]
网站：https://likeyou.cool/

**Comment by volfclub** [comment]
您是否在您的网站上放置开往的外链或徽标？

**Comment by coder-lida** [comment]
马上加上



---原始邮件---
发件人: "逊狼"<notifications@github.com&gt;
发送时间: 2020年7月5日(周日) 下午4:03
收件人: "volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送: "coder-lida"<849998287@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [volfclub/travellings] 一觉睡到小时候 (#177)




 
您是否在您的网站上放置开往的外链或徽标？

**Comment by volfclub** [comment]
依旧没找到，抱歉😥
