### ISSUE TITLE
Zi_Gao的小站

### ISSUE THREAD

**Issue by Zi-Gao** [volfclub/travellings#182]
## 网站名称
Zi_Gao的小站
## 网站链接
https://blog.zigao.info/
## 徽标位置
右侧边栏
## 推荐理由
优质原创

换地址了，重新收录一般，谢谢

**Comment by volfclub** [comment]
![image](https://user-images.githubusercontent.com/47265026/85023079-d2f23e80-b1a6-11ea-89e2-d989f61fe71f.png)
没找到。以及建议放在顶栏或侧栏导航等可以直接看到的地方

**Comment by volfclub** [comment]
请在侧栏插入开往外链

**Comment by volfclub** [comment]
博客已停止工作
