### ISSUE TITLE
魏巍申请收录

### ISSUE THREAD

**Issue by boxcheese** [volfclub/travellings#185]
## 网站名称
魏巍
## 网站链接
https://paperbox.xyz/
## 徽标位置
底栏，顶栏
## 推荐理由
三合一，一站式网站，从推荐文章到技术文章，再到我们的导航，给大家带来方便，当然本站点不和以前一样天天被攻击了，速度有了大幅度提升，之前的美文网就包含在内，忘添加

**Comment by volfclub** [comment]
已更新
