### ISSUE TITLE
房东的猫's Bolg

### ISSUE THREAD

**Issue by flag-mac** [volfclub/travellings#188]
## 网站名称
房东的猫's Bolg
## 网站链接
https://www.fddmao.com
## 徽标位置
侧栏
## 推荐理由
想加入开往这个大家庭！

**Comment by volfclub** [comment]
已收录

**Comment by ccquan** [comment]
OK

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/9c3a53c4-c6d6-4d10-a84b-7ae8ce0895e9)
确认过期，已移除，感谢支持，欢迎重新申请
