### ISSUE TITLE
anonymous's blog

### ISSUE THREAD

**Issue by passerby223** [volfclub/travellings#189]
## 网站名称
anonymous's blog
## 网站链接
https://www.wenbin.org.cn
## 徽标位置
底部页脚
## 推荐理由
逛github的时候无意看到了这个(都是猿粪)，感觉很有意思，支持一下~

**Comment by volfclub** [comment]
建议在顶部导航加入开往的外链

**Comment by passerby223** [comment]
> 建议在顶部导航加入开往的外链

已添加到`全局页头`中，我顺便把全局页脚的也保留下来了。辛苦再给复验下哈~

**Comment by volfclub** [comment]
已收录

**Comment by passerby223** [comment]
您好,我看了下`travellings/assets/travelling.js`文件里的博客地址，发现没有我的啊，可以再给我的博客`https://www.wenbin.org.cn`加上嘛

**Comment by passerby223** [comment]
Done!

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月

**Comment by HowieHz** [comment]
遗留未删除，今日巡查站点 404，已补删

![Image](https://github.com/user-attachments/assets/d372183f-b3f0-48c5-a40c-5a993d598b9f)
