### ISSUE TITLE
果子酱的博客

### ISSUE THREAD

**Issue by cwxyr** [volfclub/travellings#19]
## 网站名称
果子小酱-->https://sublimerui.top
Sakura-->https://cwxyr.me
## 网站链接
技术博客：https://sublimerui.top
生活博客：https://cwxyr.me
## 徽标位置
两个都是顶栏和底部
## 推荐理由
遇见新朋友，学习知识，分享生活

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
