### ISSUE TITLE
小新在GitHub的新窝

### ISSUE THREAD

**Issue by gudaonanfeng** [volfclub/travellings#192]
## 网站名称
小新在GitHub的新窝
## 网站链接
https://hexo.flyyi.top/
## 徽标位置
顶栏
## 推荐理由
小新的博客

**Comment by volfclub** [comment]
博客会持续更新吗

**Comment by gudaonanfeng** [comment]
博客近期更新频率可能会少但会长期存在并更新

**Comment by volfclub** [comment]
建议在博客内容充足时再来申请次
