### ISSUE TITLE
独人欣赏

### ISSUE THREAD

**Issue by drxs** [volfclub/travellings#195]
## 网站名称
独人欣赏
## 网站链接
https://www.wangyusong.cn
## 徽标位置
侧栏
## 推荐理由
个人博客，记录学习与生活

**Comment by volfclub** [comment]
建议将开往放在顶栏，打开网页即可看到的地方

**Comment by drxs** [comment]
> 建议将开往放在顶栏，打开网页即可看到的地方

已经添加好了

**Comment by volfclub** [comment]
已收录

**Comment by drxs** [comment]
已将指向域名修改为https://travellings.link

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
