### ISSUE TITLE
吃螃蟹

### ISSUE THREAD

**Issue by CrownDaisy** [volfclub/travellings#2]

**Comment by volfclub** [comment]
网站打开不开，检查下网址是否正确？

**Comment by CrownDaisy** [comment]
> 网站打开不开，检查下网址是否正确？

确认能打开，手机电脑都试了。
如果有开梯子可以关掉试试。

**Comment by volfclub** [comment]
测试了下，国内很多节点无法解析ip，优化下试试？

**Comment by CrownDaisy** [comment]
> 测试了下，国内很多节点无法解析ip，优化下试试？

已优化。
徽标位置改为首页。更明显。

**Comment by volfclub** [comment]
已收录，感谢

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
