### ISSUE TITLE
zcmimi's blog

### ISSUE THREAD

**Issue by zcmimi** [volfclub/travellings#201]
## 网站名称

zcmimi's blog

## 网站链接

https://blog.zcmimi.top

## 徽标位置

侧栏(手动展开) 、 友链

## 推荐理由

算法学习笔记

技术交流分享

刷题记录分享

**Comment by volfclub** [comment]
建议顶栏导航插入开往外链

**Comment by zcmimi** [comment]
@volfclub  添加好了

**Comment by volfclub** [comment]
已收录
