### ISSUE TITLE
🧭 申请收录示例

### ISSUE THREAD

**Issue by volfclub** [volfclub/travellings#203]
## 网站名称
狼牌工作网址导航
## 网站链接
https://www.volf.club/
## 徽标位置
侧栏（⚠ 打开网页后能直接看到）
## 推荐理由
分享我收集的网站

**Comment by XuxuGood** [comment]
网站名称
Xu's Blog

## 网站链接
https://hasaik.com

## 徽标位置
侧栏（⚠ 打开网页后能直接看到）

推荐理由
分享技术，希望能收录

**Comment by lingfengwusheng** [comment]
##网站名称
提莫酱的博客
##网站链接
https://zzr3.xyz
##徽标位置
网页正上方 ”开往“按钮
##推荐理由
分享友联-开放

**Comment by foxscallion11** [comment]
## 网站名称
FoxScallion博客

## 网站链接
https://www.foxscallion.top/

## 徽标位置
底部
## 推荐理由
分享我收集的网站，技术类、生活类，分享我生活上的一些感悟

**Comment by TonyMichaeLi** [comment]
网站名称
Tony's blog

网站链接
[https://www.tonylsl.top/](https://www.tonylsl.top/)

徽标位置
底栏（⚠ 打开网页后能直接看到）

推荐理由
分享我收集的网站

**Comment by unluckynike** [comment]
网站名称
吴李曾

网站链接
https://www.wulinzeng.vip/

徽标位置
底栏（⚠ 打开网页后能直接看到）

推荐理由
分享学习编程历程，热爱生活。

**Comment by sangxuesheng** [comment]
网站名称
听闻.

网站链接
https://www.sangxuesheng.com

徽标位置
侧栏（⚠ 打开网页后能直接看到）

推荐理由
分享学习编程历程，热爱生活。

**Comment by volfclub** [comment]
请注意，申请加入要自己提一个 issue ，而非回复这个例子
