### ISSUE TITLE
ZigZagK的博客

### ISSUE THREAD

**Issue by ZigZagK** [volfclub/travellings#206]
## 网站名称

ZigZagK的博客

## 网站链接

[https://zigzagk.top/](https://zigzagk.top/)

## 徽标位置

底部左侧

## 推荐理由

个人博客，更新随笔和一些技术向的内容

**Comment by volfclub** [comment]
请在顶部导航放置开往外链

**Comment by ZigZagK** [comment]
> 请在顶部导航放置开往外链

顶部导航不方便添加，能否只在底部添加呢QAQ

**Comment by volfclub** [comment]
本质要求是打开网页后就能看到开往，位置要求并不固定

**Comment by ZigZagK** [comment]
> 本质要求是打开网页后就能看到开往，位置要求并不固定

抱歉上周高考没有时间调整，现在已经在顶栏和底部同时放置图标

由于手机端太窄，因此手机端顶栏图标隐藏了，求放过QAQ

**Comment by volfclub** [comment]
已收录
