### ISSUE TITLE
TF的博客

### ISSUE THREAD

**Issue by htf6782414** [volfclub/travellings#207]
## 网站名称
TF的博客
## 网站链接
https://blog.tengfei.website/
## 徽标位置
侧栏（⚠ PC打开网页后能直接看到）
折叠菜单（手机版需点击顶部的汉堡菜单）
## 推荐理由
觉得这个项目很有意思，希望加入

**Comment by volfclub** [comment]
已收录

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已移除开往链接，现已将您移除，如需加入开往，可再次按照流程申请。 @htf6782414

**Comment by HowieHz** [comment]
手动巡查，站点状态正常
