### ISSUE TITLE
Dragon's Blog

### ISSUE THREAD

**Issue by ExplodingFKL** [volfclub/travellings#208]
## 网站名称
Dragon's Blog

## 网站链接
https://blog.open-edgn.tech/
## 徽标位置

在顶部导航栏名为 "TRAVELLINGS" 的选项

## 推荐理由
周记总结以及一些关于软件开发的随想

**Comment by volfclub** [comment]
好奇怪的博客啊，没看到什么内容的样子，很多还是加密的……歪比巴卜？

**Comment by ExplodingFKL** [comment]
> 好奇怪的博客啊，没看到什么内容的样子，很多还是加密的……歪比巴卜？

欸 ....

**Comment by ExplodingFKL** [comment]
> 好奇怪的博客啊，没看到什么内容的样子，很多还是加密的……歪比巴卜？

欸 .... 内容太少啦，那内容充足后我再来申请吧
