### ISSUE TITLE
Oasis's Blog

### ISSUE THREAD

**Issue by ghost** [volfclub/travellings#21]
## 网站名称
Oasis's Blog
## 网站链接
https://blog.imoasis.cn
## 徽标位置
顶部链接，底部图标
## 推荐理由
高三学生日常不务正业（笑

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
