### ISSUE TITLE
满月客栈

### ISSUE THREAD

**Issue by wibus-wee** [volfclub/travellings#210]
## 网站名称
满月技术君
## 网站链接
http://jishujun.com
## 徽标位置
导航栏左侧(开往-远方）
## 推荐理由
分享原创知识，优质文章，几乎是啥都搞

**Comment by volfclub** [comment]
已收录

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/99a8ad56-cced-45c0-b0ce-dda09cf2e9a4)
确认域名过期，已删除，感谢支持，欢迎重新申请加入开往！
