### ISSUE TITLE
Zi_Gao的小站

### ISSUE THREAD

**Issue by Zi-Gao** [volfclub/travellings#211]
## 网站名称
Zi_Gao的小站
## 网站链接
https://blog.zigao.info
## 徽标位置
左侧
## 推荐理由
优质内容

更新徽标位置...

**Comment by volfclub** [comment]
您的博客打不开了……

**Comment by Zi-Gao** [comment]
被ddos不好意思,网站现在一般在14:00--20:00会开放

**Comment by volfclub** [comment]
依旧无法访问
