### ISSUE TITLE
Colsrch'Blog

### ISSUE THREAD

**Issue by Colsrch** [volfclub/travellings#212]
## 网站名称
Colsrch'Blog
## 网站链接
https://colsrch.top
## 徽标位置
侧边栏导航区域（PC直接可见，手机需划至页面底部)
侧边栏望远镜图标（与侧边栏导航区域图标一致，PC直接可见，手机需划至页面底部）
顶部导航条（‘小功能’菜单中）
页面底部望远镜图标（与侧边栏导航区域图标一致）
## 推荐理由
- 已强制启用https
- 网站正常更新维护中
- 将自己的优质内容分享给他人

**Comment by volfclub** [comment]
已收录
