### ISSUE TITLE
SkYe's Blog

### ISSUE THREAD

**Issue by skyedai910** [volfclub/travellings#217]
## 网站名称

SkYe's Blog

## 网站链接

https://www.mrskye.cn/

## 徽标位置

顶栏右侧

## 推荐理由

个人博客，更新ctf和信息安全二进制向的内容

**Comment by volfclub** [comment]
建议放在左侧导航，写明开往字样

**Comment by skyedai910** [comment]
已修改到左侧导航，请验证

**Comment by volfclub** [comment]
已收录
