### ISSUE TITLE
Mr.Sen 申请收录

### ISSUE THREAD

**Issue by NorthCityChen** [volfclub/travellings#22]
## 网站名称
Mr.Sen
## 网站链接
https://449293786.site
## 徽标位置
顶部链接，底部图标
## 推荐理由
来这里看看吧，也许会有意想不到的收获

**Comment by volfclub** [comment]
没发现已放置的徽标？

**Comment by NorthCityChen** [comment]
> 
> 
> 没发现已放置的徽标？

添加了

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
