### ISSUE TITLE
开心果个人博客

### ISSUE THREAD

**Issue by zhw150** [volfclub/travellings#220]
## 网站名称
开心果个人博客
## 网站链接
https://zhw150.top
## 徽标位置
侧栏/顶栏(打开可直接看到)
## 推荐理由
专注于资源分享

**Comment by volfclub** [comment]
建议写明开往

**Comment by zhw150** [comment]
已按照要求更改，辛苦了



---原始邮件---
发件人: "逊狼"<notifications@github.com&gt;
发送时间: 2020年7月6日(周一) 晚上8:57
收件人: "volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送: "zhw150"<319951621@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [volfclub/travellings] 开心果个人博客 (#220)




 
建议写明开往

**Comment by volfclub** [comment]
已收录
