### ISSUE TITLE
幻想伏特伽

### ISSUE THREAD

**Issue by koogllz** [volfclub/travellings#224]
## 网站名称
幻想伏特伽 — 产品商业化
## 网站链接
www.koogllz.com
## 徽标位置
博客底部
## 推荐理由
互联网商业化知识分享 | 计算广告领域

**Comment by volfclub** [comment]
请在打开网页后可以直接看到的地方，如顶部导航添加外链

**Comment by koogllz** [comment]
好的，已修改，请查阅

**Comment by volfclub** [comment]
![图片](https://user-images.githubusercontent.com/47265026/95031286-cc50ee00-06e7-11eb-98a3-c1299be7d4e3.png)
网站似乎工作的不正常
