### ISSUE TITLE
靜海遺跡

### ISSUE THREAD

**Issue by voidge** [volfclub/travellings#225]
## 网站名称
靜海遺跡
## 网站链接
<https://voidge.github.io>
## 徽标位置
底部
## 推荐理由
Competitive programming ~~水文大全~~

**Comment by volfclub** [comment]
请在打开网页后可以直接看到的地方，如顶部导航添加外链

**Comment by voidge** [comment]
> 请在打开网页后可以直接看到的地方，如顶部导航添加外链

移到 navbar 了

**Comment by volfclub** [comment]
https://voidge.cf/

**Comment by volfclub** [comment]
已收录
