### ISSUE TITLE
Kiritoghy's Blog网站的名字

### ISSUE THREAD

**Issue by kiritoghy** [volfclub/travellings#229]
## 网站名称
Kiritoghy's Blog
## 网站链接
https://www.kiritoghy.cn/
## 徽标位置
顶部菜单
## 推荐理由
感觉很有趣的样子，希望能加入到这个项目

**Comment by volfclub** [comment]
已收录

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页未使用SSL，现已将您移除，如需加入开往，可再次按照流程申请。 @kiritoghy
