### ISSUE TITLE
BORBER 的收录申请

### ISSUE THREAD

**Issue by Borber** [volfclub/travellings#234]
## 网站名称
BORBER
## 网站链接
https://www.cnblogs.com/borber/
## 徽标位置
顶部
## 推荐理由
分享各种有用 有趣的东西 | 个人博客 | 很喜欢这个项目的概念

**Comment by volfclub** [comment]
已收录

**Comment by Borber** [comment]
博客地址已更改为 https://blog.borber.top/ 望修改
