### ISSUE TITLE
Loafing,cn 申请收录

### ISSUE THREAD

**Issue by forliuyifei** [volfclub/travellings#238]
## 网站名称
若风
## 网站链接
https://loafing.cn/
## 徽标位置
顶栏
## 推荐理由
尽量做减法，保持轻量极速。多做文字记录，少一些花里胡哨。

**Comment by forliuyifei** [comment]
奇怪, 我点错逗号了吗?

**Comment by volfclub** [comment]
已收录

**Comment by forliuyifei** [comment]
> 您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下： gif动图：https://www.travellings.cn/assets/logo.gif svg：https://www.travellings.cn/assets/logo.svg 请您及时更换相关地址，谢谢配合。

已更新
