### ISSUE TITLE
lxxs的小屋申请收录

### ISSUE THREAD

**Issue by Mlxxs** [volfclub/travellings#24]
## 网站名称
lxxs的小屋
## 网站链接
https://lxxs.xyz
## 徽标位置
底部右端
## 推荐理由
希望参与这个项目。

**Comment by volfclub** [comment]
建议在侧栏导航或其他直观的地方再放置一个开往的外链。
https://github.com/volfclub/travellings#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by Mlxxs** [comment]
好的，希望能尽快通过

**Comment by volfclub** [comment]
好，修改后请回复

**Comment by Mlxxs** [comment]
已经OK，在左侧栏。

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
