### ISSUE TITLE
风月平分破

### ISSUE THREAD

**Issue by ghost** [volfclub/travellings#240]
## 网站名称
风月平分破
## 网站链接
https://www.1-365.cn/
## 徽标位置
底栏
## 推荐理由
一个爱诗博主的技术分享网站

**Comment by volfclub** [comment]
请在打开网页后可以直接看到的地方，如顶部导航添加外链

**Comment by mlgb404** [comment]
已重新在导航栏添加外链，但是由于导航栏在打开网页后处于自动隐藏的状态，因此需要向下滚动页面才可以看见导航栏

**Comment by volfclub** [comment]
已收录
