### ISSUE TITLE
新漫猫

### ISSUE THREAD

**Issue by SteamFinder** [volfclub/travellings#245]
## 网站名称
新漫猫
## 网站链接
https://www.acg19.top   _[1]_
## 徽标位置
_[1]_ 页脚
## 推荐理由
ACG爱好者讨论以及多领域的内容，会有一些有趣的东西
如[网易云自动打卡升级API](https://netease-music-api.acg19.top)

**Comment by volfclub** [comment]
您的内容是否合规呢？

**Comment by SteamFinder** [comment]
> 您的内容是否合规呢？

具体指哪方面

**Comment by SteamFinder** [comment]
> 您的内容是否合规呢？

请详细说明

**Comment by volfclub** [comment]
一般而言，不会将“视频资源分享”为主的网站加进来，除非你分享的内容是有授权，或是你的网站能稳定长久运行下去

**Comment by SteamFinder** [comment]
> 一般而言，不会将“视频资源分享”为主的网站加进来，除非你分享的内容是有授权，或是你的网站能稳定长久运行下去

网站能够稳定长久运行，且内容不只是分享，分享只是用户交流的附加产品，主要是为了交流水贴

**Comment by SteamFinder** [comment]
> 一般而言，不会将“视频资源分享”为主的网站加进来，除非你分享的内容是有授权，或是你的网站能稳定长久运行下去

由于申请为20天前发出的，当时网站管理较混乱，经过不断更新迭代，现在基本完善对于网站的定位
我认为是一个多领域的，各种功能兼备的，推荐理由现已修改

**Comment by SteamFinder** [comment]
> ## 网站名称
> 新漫猫
> 
> ## 网站链接
> https://forum.acg19.top _[1]_
> https://www.acg19.top _[2]_
> 
> ## 徽标位置
> _[1]_ 欢迎横幅（正上方）
> _[2]_ 页脚
> 
> ## 推荐理由
> ACG爱好者讨论以及多领域的内容，会有一些有趣的东西
如[网易云自动打卡升级API](https://netease-music-api.acg19.top)

**Comment by volfclub** [comment]
还有些个问题，你的第一个网站开往外链是由 flarum 的通知中，用户第一次浏览后就消失了，不符合我们的要求，建议放在顶部导航以外链的形式。
或者收录第二个网站，但开往的外链并不能打开网页后就看到，请调整下。

**Comment by SteamFinder** [comment]
> 还有些个问题，你的第一个网站开往外链是由 flarum 的通知中，用户第一次浏览后就消失了，不符合我们的要求，建议放在顶部导航以外链的形式。
> 或者收录第二个网站，但开往的外链并不能打开网页后就看到，请调整下。

我稍后进行修改

**Comment by SteamFinder** [comment]
> 还有些个问题，你的第一个网站开往外链是由 flarum 的通知中，用户第一次浏览后就消失了，不符合我们的要求，建议放在顶部导航以外链的形式。
> 或者收录第二个网站，但开往的外链并不能打开网页后就看到，请调整下。

已经调整完成，请再次审核

**Comment by volfclub** [comment]
两个网址打开的页面似乎一致

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
