### ISSUE TITLE
风渐远申请收录

### ISSUE THREAD

**Issue by 0xNaraku** [volfclub/travellings#25]
## 网站名称
风渐远

## 网站链接
https://www.naraku.cn/

## 徽标位置
页面侧栏

## 推荐理由
这个想法很有趣，希望参与！

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已移除开往链接，现已将您移除，如需加入开往，可再次按照流程申请。
