### ISSUE TITLE
有梦想的咸鱼

### ISSUE THREAD

**Issue by xianyum** [volfclub/travellings#252]
## 网站名称
有梦想的咸鱼
## 网站链接
https://xianyum.cn/
## 徽标位置
网页正上方。”开往“按钮
## 推荐理由
每2~3天分享一篇it相关博客。百二秦关终属楚,三千越甲可吞吴

**Comment by volfclub** [comment]
博客内容有些少，要不再写写？

**Comment by xianyum** [comment]
大佬 不少了呀 都十篇了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "volfclub/travellings"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月9日(星期天) 晚上9:26
收件人:&nbsp;"volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送:&nbsp;"故事还很长"<80616059@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [volfclub/travellings] 有梦想的咸鱼 (#252)





 
博客内容有些少，要不再写写？

**Comment by volfclub** [comment]
已收录
