### ISSUE TITLE
可定博客

### ISSUE THREAD

**Issue by cordinovet** [volfclub/travellings#253]
## 网站名称
可定博客
## 网站链接
https://wnag.com.cn/
## 徽标位置
顶栏
## 推荐理由
分享知识，传递知识

**Comment by volfclub** [comment]
抱歉，没有找到外链在哪

**Comment by cordinovet** [comment]
你好，在网页顶部导航栏有“开往”字样，在网页底部同样有“Travelling”字样。

**Comment by volfclub** [comment]
已收录

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已无法访问，现已将您移除，如需加入开往，可再次按照流程申请。 @cordinovet

**Comment by HowieHz** [comment]
遗留未删除，已补删
