### ISSUE TITLE
大海的页面

### ISSUE THREAD

**Issue by SEA03745A** [volfclub/travellings#255]
## 网站名称
大海的页面
## 网站链接
https://ccccc.cyou
## 徽标位置
页面顶栏
## 推荐理由
一名普通的初中生的页面

**Comment by SEA03745A** [comment]
gkdgkd

**Comment by SEA03745A** [comment]
gkd

**Comment by volfclub** [comment]
请在打开页面就能看到的位置放置开往的链接，如顶部导航

**Comment by SEA03745A** [comment]
> 请在打开页面就能看到的位置放置开往的链接，如顶部导航

好了，再看看哈

**Comment by SEA03745A** [comment]
> 请在打开页面就能看到的位置放置开往的链接，如顶部导航

gkdgkd

**Comment by SEA03745A** [comment]
> 请在打开页面就能看到的位置放置开往的链接，如顶部导航

已经好了，再看看

**Comment by volfclub** [comment]
已收录
