### ISSUE TITLE
Zeruns's Blog申请

### ISSUE THREAD

**Issue by zeruns** [volfclub/travellings#26]
## 网站名称
Zeruns's Blog

## 网站链接
https://blog.zeruns.tech

## 徽标位置
全站底部和友情链接页

## 推荐理由
这个想法很有趣，希望参与！

**Comment by volfclub** [comment]
建议在侧栏导航或其他直观的地方再放置一个开往的外链。
https://github.com/volfclub/travellings#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by zeruns** [comment]
> 建议在侧栏导航或其他直观的地方再放置一个开往的外链。
> https://github.com/volfclub/travellings#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

已改左侧导航

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
