### ISSUE TITLE
Funix‘s blog

### ISSUE THREAD

**Issue by ImFyatto** [volfclub/travellings#260]
## 网站名称
Funix’s blog
## 网站链接
https://www.funix.cn
## 徽标位置
侧栏靠下位置
## 推荐理由
无意间看到这个社区，瞬间被随机推荐吸引了，超级想加入～

**Comment by volfclub** [comment]
嗨，建议将“开往”放在打开网页就能看到的地方，如你的顶栏，或侧栏靠上的位置

**Comment by ImFyatto** [comment]
@volfclub 已修改，望通过

**Comment by volfclub** [comment]
已收录
