### ISSUE TITLE
憨憨的日常

### ISSUE THREAD

**Issue by PandaQ1** [volfclub/travellings#262]
## 网站名称
憨憨的日常
## 网站链接
https://www.hx1s.com/
## 徽标位置
底栏靠右
## 推荐理由
希望能认识更多的小伙伴

**Comment by volfclub** [comment]
抱歉，没有找到。建议放在顶栏

**Comment by PandaQ1** [comment]
> 抱歉，没有找到。建议放在顶栏

已经放置在顶栏。感谢。

**Comment by volfclub** [comment]
![图片](https://user-images.githubusercontent.com/47265026/95033338-6a48b680-06f0-11eb-8772-ebf00c8564a4.png)
您好，似乎依旧没有在顶栏找到

**Comment by PandaQ1** [comment]
不好意思哈，由于最近比较忙，先关闭issue了。后面再来弄，辛苦了。
