### ISSUE TITLE
自说自话

### ISSUE THREAD

**Issue by viphiker** [volfclub/travellings#264]
抱歉，之前在上课的时候没有打理好服务器导致无人续费，服务器过期，数据也全部丢了，目前打算重新开始，做一个全新方向的博客，希望还能再加入开往这个大家庭！

## 网站名称

自说自话

## 网站链接

https://7e.re

## 徽标位置

顶栏

## 推荐理由

一些关于PHP 网络安全 或者我的一些小项目等交流思维和切磋技艺的个人博客

**Comment by volfclub** [comment]
无法访问
