### ISSUE TITLE
阳光派Plus

### ISSUE THREAD

**Issue by zyoushuo** [volfclub/travellings#266]
## 网站名称
阳光派Plus
## 网站链接
https://www.zyoushuo.cn/
## 徽标位置
导航栏
## 推荐理由
分享快乐

**Comment by volfclub** [comment]
内容有些少，要不再写写

**Comment by zyoushuo** [comment]
好的，偷懒了，哈哈

**Comment by zyoushuo** [comment]
> 内容有些少，要不再写写

好的，偷懒了，哈哈
