### ISSUE TITLE
Codinglink's Blog-林克的编程小记

### ISSUE THREAD

**Issue by CodingLink** [volfclub/travellings#268]
## 网站名称
Codinglink's Blog-林克的编程小记
## 网站链接
https://www.codinglink.tech
## 徽标位置
侧栏
## 推荐理由
技术分享、读书笔记分享

**Comment by volfclub** [comment]
建议放在顶栏，或侧栏靠上的位置

**Comment by CodingLink** [comment]
修改了，放在顶栏了

**Comment by CodingLink** [comment]
> 
> 
> 建议放在顶栏，或侧栏靠上的位置

修改了，已放在顶栏

**Comment by CodingLink** [comment]
@volfclub

**Comment by volfclub** [comment]
已收录
