### ISSUE TITLE
风也温柔博客申请

### ISSUE THREAD

**Issue by kaygb** [volfclub/travellings#27]
## 网站名称
风也温柔
## 网站链接
https://eas1.cn
## 徽标位置
全站底部
## 推荐理由
这个项目很有趣，同时也为个人博客圈子发力！

**Comment by zeruns** [comment]
嘿嘿

**Comment by volfclub** [comment]
建议在侧栏导航或其他直观的地方再放置一个开往的外链。
抱歉看有回复了误以为已经处理了。

**Comment by kaygb** [comment]
已经在侧栏添加

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
