### ISSUE TITLE
BD的小窝

### ISSUE THREAD

**Issue by BluesDawn576** [volfclub/travellings#277]
## 网站名称
BD的小窝
## 网站链接
https://www.bluesdawn.top/
## 徽标位置
顶栏与侧栏
## 推荐理由
记录生活与学习，希望可以遇到更多的dalao学习

**Comment by volfclub** [comment]
内热有些少，要不再写写？

**Comment by BluesDawn576** [comment]
行吧（）

**Comment by volfclub** [comment]
已收录
