### ISSUE TITLE
XiYo吧 申请收录

### ISSUE THREAD

**Issue by xiyo520** [volfclub/travellings#28]
## 网站名称
XiYo吧
## 网站链接
https://www.xiyo8.cn/
## 徽标位置
全站底部
## 推荐理由
草根站长互帮互助

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
