### ISSUE TITLE
SurpriseLon's blog

### ISSUE THREAD

**Issue by SurpriseLon** [volfclub/travellings#285]
## 网站名称
SurpriseLon
## 网站链接
https://furrysp.me
## 徽标位置
顶栏和底栏
## 推荐理由
收集一些技术文章

**Comment by volfclub** [comment]
![image](https://user-images.githubusercontent.com/47265026/91658685-fddd0500-eafc-11ea-81a2-83a220b377ab.png)
你的网站底部似乎有些不正常

**Comment by volfclub** [comment]
网页似乎打不开

**Comment by volfclub** [comment]
网页底部就是这样设计的吗？

**Comment by SurpriseLon** [comment]
抱歉，这几个月我一直在整顿网站，所以没看到您的回复，开往链接已经放好了，并且网站可以正常访问
https://furrysp.me/
