### ISSUE TITLE
黑石博客

### ISSUE THREAD

**Issue by heson525** [volfclub/travellings#286]
## 网站名称
黑石博客
## 网站链接
https://www.heson10.com
## 徽标位置
首页导航
## 推荐理由
原创hexo折腾，资深老博主回归。
文章偏技术类，后期注重写生活类。

**Comment by volfclub** [comment]
建议将开往放在打开网页能直接看到的地方

**Comment by heson525** [comment]
已改到首页  ![Snipaste_2020-08-30_20-18-11](https://picup.heson10.com/img/Snipaste_2020-08-30_20-18-11.png)

刷新可看到。
> 建议将开往放在打开网页能直接看到的地方

**Comment by heson525** [comment]
请问下，这都挂了一个月，请问能更新吗？至少说个收录时间吧，时间不充足需要人手共同维护仓库不？😂

**Comment by heson525** [comment]
移植了一款TYPECHO付费主题，换了位置。首页顶栏，如图：
![image](https://user-images.githubusercontent.com/32234343/94889577-3df22780-04af-11eb-810b-edd9c4f65785.png)

**Comment by heson10** [comment]
看到老狼在审核，求通过呀。

**Comment by volfclub** [comment]
亲，网页似乎挂了？

**Comment by heson10** [comment]
没有啊。不会吧

**Comment by heson10** [comment]
https://www.heson10.com/

**Comment by heson10** [comment]
请问显示啥？我用的又拍云  heson525.vercel.app  的源站。应该不至于啊，我这边是好的。请问哪里的宽带？

**Comment by volfclub** [comment]
![图片](https://user-images.githubusercontent.com/47265026/95179341-14106c00-07f3-11eb-81b2-d6c3b2c94028.png)
可能cdn有问题吧

**Comment by heson10** [comment]
我这是朋友没反应有这个问题，还请收录下。我再看看是不是共性问题。

**Comment by heson10** [comment]
审核暂时请访问  heson525.vercel.app

**Comment by heson10** [comment]
审核暂时请访问  heson525.vercel.app

**Comment by heson10** [comment]
查了下火狐浏览器设置问题，帮忙看下其他浏览器是否正常。谢谢。

**Comment by heson10** [comment]
https://www.firefox.net.cn/read-34579

找到大概率原因。

**Comment by heson525** [comment]
![图片](https://user-images.githubusercontent.com/32234343/95189410-66a45500-0800-11eb-88c1-e8bf490b106e.png)
这是网站的检测数据。并无异常。

**Comment by volfclub** [comment]
目前测试了下，没有问题了。
稍后收录

**Comment by heson525** [comment]
> 目前测试了下，没有问题了。
> 稍后收录

感谢

**Comment by volfclub** [comment]
![图片](https://user-images.githubusercontent.com/47265026/95209864-6797af80-081d-11eb-9ffe-30007390914e.png)
很奇怪，https://www.heson10.com 又工作不正常了。我尝试了谷歌火狐都有问题。
还尝试了下一些分析网站，也报错了，不能捕获你网站正常打开的图像。

**Comment by heson525** [comment]
分析网站发我一下

**Comment by heson525** [comment]
在网页头加上了<meta http-equiv="Content-Type" content="text/html">   已经修复好，请强制刷新试试

**Comment by heson10** [comment]
改好了，审核一下呗。

**Comment by volfclub** [comment]
已收录
