### ISSUE TITLE
锴|一个神奇的角落 申请收录

### ISSUE THREAD

**Issue by wangkai6688** [volfclub/travellings#29]
## 网站名称
锴|一个神奇的角落
## 网站链接
https://www.wangkai88.com
## 徽标位置
左侧导航栏、全站右下
## 推荐理由
要有最朴实的生活和最遥远的梦想，即使明天天寒地冻、山高水远、路远马亡。

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已移除开往链接，现已将您移除，如需加入开往，可再次按照流程申请。 @Sorkai

**Comment by HowieHz** [comment]
今日巡查发现，先前未能成功移除，进行再次移除操作
