### ISSUE TITLE
KiteAB's Blog

### ISSUE THREAD

**Issue by KiteAB** [volfclub/travellings#291]
## 网站名称
KiteAB's Blog
## 网站链接
https://kiteab.ga
## 徽标位置
页首(能直接看到)/页尾
## 推荐理由
不定时分享好玩的东西

**Comment by volfclub** [comment]
文章似乎有些少，要不再写写？

**Comment by KiteAB** [comment]
没啥问题   我很多内容都在b站  以后b站的视频的文字稿会搬到blog来  可以先合并下  顺便清查下无用网站

**Comment by volfclub** [comment]
好的。欢迎搬运的差不多了回下这个issue

**Comment by volfclub** [comment]
欢迎重新打开
