### ISSUE TITLE
YunFanCH · 云帆沧海

### ISSUE THREAD

**Issue by yunfanch** [volfclub/travellings#294]
### 网站名称

> 

 YunFanCH · 云帆沧海

<hr />

### 网站链接

> 

 https://yunfanch.com

<hr />

### 徽标位置

> 

导航栏+底部

<hr />

### 推荐理由

> 

一切过往，皆为序章。直挂云帆，乘风破浪。

<hr />

**Comment by yunfanch** [comment]
项目还维护吗？添加有段时间了，，，，，8月23 - 10.05日   暂时先撤下了。

**Comment by volfclub** [comment]
很巧，正在审核中，先挂一下吧

**Comment by yunfanch** [comment]
真的好巧，马上再加上

**Comment by yunfanch** [comment]
> 很巧，正在审核中，先挂一下吧

已经加上了

**Comment by volfclub** [comment]
![图片](https://user-images.githubusercontent.com/47265026/95675248-633a1080-0be8-11eb-8968-67419bd2d9fb.png)
您好，已经收录了，还没push
漏掉回复你让你久等了，抱歉

**Comment by yunfanch** [comment]
好的，我还以为没通过呢
