### ISSUE TITLE
非礼勿言 申请加入开往

### ISSUE THREAD

**Issue by yelincx** [volfclub/travellings#30]
## 网站名称
非礼勿言
## 网站链接
https://feiliwuyan.com
## 徽标位置
侧栏和底部都已设置好
## 推荐理由
很好的想法，来支持一下，希望未来能有更好的网络环境。
博主描述：博士，海外华夏骑士，分享所见所闻所感所悟等。

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
