### ISSUE TITLE
Kagurain的百草园

### ISSUE THREAD

**Issue by kagurain** [volfclub/travellings#304]
## 网站名称
Kagurain的百草园
## 网站链接
https://static-x.work
## 徽标位置
侧边栏（全站）
## 推荐理由
沙雕网友 | 网站服务器攻防安全 | 运维技术分享 | PHP实用小技巧

（今天刚建站 数据会补回来的！qwq）

**Comment by kagurain** [comment]
域名已更换为 iili.me

**Comment by volfclub** [comment]
Never Online.Don't aky me why.
