### ISSUE TITLE
野肆的生活分享

### ISSUE THREAD

**Issue by yexsi** [volfclub/travellings#307]

**Comment by volfclub** [comment]
文章有些少，要不再写写

**Comment by yexsi** [comment]
前几日网站重新部署，原来的文章还没有添加上。近日就会全部补齐，还请收录网站，谢谢！

**Comment by volfclub** [comment]
建议放在顶部导航等打开网页就能看到的地方。
欢迎博客恢复好后，回一下这个 issues。

**Comment by yexsi** [comment]
已将徽标添加至网页全局侧边栏中，文章内容已恢复完毕。还请收录，谢谢！

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
