### ISSUE TITLE
MBR的博客

### ISSUE THREAD

**Issue by MBRjun** [volfclub/travellings#319]
## 网站名称
MBR的博客 / MBR's Blog
## 网站链接
https://blog.mbrjun.cn/
## 徽标位置
左侧边栏
## 推荐理由
技术学生党的日常分享

**Comment by volfclub** [comment]
建议放在侧栏导航打开网页就能直接看到的地方

**Comment by MBRjun** [comment]
放到左侧边栏了

**Comment by BLxcwg666** [comment]
捉到MBRjun，马上恰了

**Comment by volfclub** [comment]
已收录
