### ISSUE TITLE
【申请加入】星云C馆

### ISSUE THREAD

**Issue by MarikoAsian** [volfclub/travellings#32]
## 网站名称
星云C馆
## 网站链接
https://www.m78.co
## 徽标位置
左侧边栏
## 推荐理由
设想很新颖，希望能够参与。

**Comment by MarikoAsian** [comment]
至于图标，本人自己做了一个，https://www.m78.co/demo/travelling.png

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by MarikoAsian** [comment]
30号，请求更换名称为星空小站，链接更改为https://www.m78.co
