### ISSUE TITLE
洛仙璃の幻梦

### ISSUE THREAD

**Issue by mzwing** [volfclub/travellings#322]
## 网站名称
洛仙璃の幻梦
## 网站链接
https://lxcl.gq
## 徽标位置
底部
## 推荐理由
希望学习大佬

**Comment by volfclub** [comment]
你的文章似乎有些少…
另外打开速度有些慢，如果是静态博客可以试试vercel托管

**Comment by mzwing** [comment]
好的，我会努力写作的。不过我是学生党，写作速度可能会受影响
我的Github账户是用QQ邮箱注册的，所以无法注册vercel……

**Comment by volfclub** [comment]
ok，欢迎多写写之后再来申请一次
