### ISSUE TITLE
程序员快速导航

### ISSUE THREAD

**Issue by uiuang** [volfclub/travellings#330]
## 网站名称
程序员快速导航
## 网站链接
http://www.zsc7454.cn/cn/index.html
## 徽标位置
侧边
## 推荐理由
是程序员所需要的导航网站

**Comment by volfclub** [comment]
很不错，建议修下必要的细节后，如左上角的logo图片，再来申请一次

**Comment by uiuang** [comment]
已修改，望收录

**Comment by volfclub** [comment]
还有一个必要的小问题，你的网站没开启https

**Comment by volfclub** [comment]
请注意，你的网站需要开启https，
这不是一件难事，大多数时候还是免费的，试试看。

**Comment by volfclub** [comment]
最后一次提醒，您需要开启 https
