### ISSUE TITLE
FUTURD

### ISSUE THREAD

**Issue by FloppyDisk-FD** [volfclub/travellings#335]
## 网站名称
FUTURD
## 网站链接
https://www.futurd.cn/
## 徽标位置
侧栏
## 推荐理由
分享一些实用技巧，Java自学学习笔记，对Linux颇有兴趣

**Comment by volfclub** [comment]
文章似乎有一些少，要不再写写？
建议10篇左右再申请下

**Comment by FloppyDisk-FD** [comment]
> 文章似乎有一些少，要不再写写？
> 建议10篇左右再申请下

好的
