### ISSUE TITLE
wmz's blog

### ISSUE THREAD

**Issue by wmz1024** [volfclub/travellings#337]
## 网站名称
wmz's blog
## 网站链接
wmzwsa.xyz
## 徽标位置
侧边栏
## 推荐理由
这个博客会发一些奇奇怪怪，有用的内容 ！？？

**Comment by volfclub** [comment]
建议放在顶部导航，打开网页就能直接看到的地方

**Comment by wmz1024** [comment]
> 建议放在顶部导航，打开网页就能直接看到的地方

好的

**Comment by wmz1024** [comment]
> 建议放在顶部导航，打开网页就能直接看到的地方

已经弄完了 之后呢

**Comment by volfclub** [comment]
已收录
