### ISSUE TITLE
Cheung申请收录

### ISSUE THREAD

**Issue by 1eafy** [volfclub/travellings#34]
## 网站名称
Cheung
## 网站链接
https://icheung.net
## 徽标位置
底部
## 推荐理由
有趣，想法很好，希望加入

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
