### ISSUE TITLE
失效链接

### ISSUE THREAD

**Issue by yunfanch** [volfclub/travellings#340]
https://blog.guhub.cn/

**Comment by volfclub** [comment]
测试了下，可以正常访问的样子？

**Comment by yunfanch** [comment]
![QQ图片20201011235746](https://user-images.githubusercontent.com/68909593/95683414-a4004c80-0c1d-11eb-9280-5523a0f8cee7.png)
我这里怎么连接地址错误啊 ， 打开是空白页
