### ISSUE TITLE
网站的名字

### ISSUE THREAD

**Issue by Johnsonzcode** [volfclub/travellings#352]
## 网站名称
ZJohnson's blog
## 网站链接
johnsonzzz.gitee.io
## 徽标位置
顶栏有外链，点进去有徽标和说明
## 推荐理由
生信学习者，希望能帮到同样遇到坑的人；也希望被更多人看到！

**Comment by volfclub** [comment]
抱歉，您没有使用https

**Comment by Johnsonzcode** [comment]
好的，已经修改为https，感谢您！

**Comment by volfclub** [comment]
您的博客目前只有5篇内容，建议再写写看。欢迎随时reopen
