### ISSUE TITLE
我的博客没有被收录,辛苦给添加一下呗

### ISSUE THREAD

**Issue by passerby223** [volfclub/travellings#360]
已收录

_Originally posted by @volfclub in https://github.com/volfclub/travellings/issues/189#issuecomment-646631849_

您好,我看了下`travellings/assets/travelling.js`文件里的博客地址，发现没有我的啊，可以再给我的博客`https://www.wenbin.org.cn`加上嘛

**Comment by volfclub** [comment]
抱歉，可能漏掉了，我处理下

**Comment by volfclub** [comment]
已处理

**Comment by HowieHz** [comment]
link #189
