### ISSUE TITLE
阿猫阿狗申请收录

### ISSUE THREAD

**Issue by qimiaoliaoss** [volfclub/travellings#37]
## 网站名称
阿猫阿狗
## 网站链接
https://ionssource.cn/
## 徽标位置
顶部导航栏外链、网页底部
## 推荐理由
有趣的项目，希望可以加入

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
