### ISSUE TITLE
且听书吟

### ISSUE THREAD

**Issue by syhily** [volfclub/travellings#372]
## 网站名称

且听书吟

## 网站链接

https://yufan.me

## 徽标位置

网站最底栏

## 推荐理由

坚持写了9年的原创博客，并将继续坚持下去。

**Comment by volfclub** [comment]
请将链接放在打开网页能直接看到的地方

**Comment by syhily** [comment]
> 请将链接放在打开网页能直接看到的地方

我一直都在网站底部有放置对应的链接。

**Comment by volfclub** [comment]
您可以参考下上线的网站，或今日更新的 readme

**Comment by syhily** [comment]
已经修改。

**Comment by syhily** [comment]
Close this issue cause the repository's author is too late to response.
