### ISSUE TITLE
alpaca++

### ISSUE THREAD

**Issue by alpaca-brother** [volfclub/travellings#378]
## 网站名称
alpaca++
## 网站链接
https://alpaca.plus
## 徽标位置
侧栏
## 推荐理由
这是我的个人非盈利性博客站点，已经运稳定行了200多天，MySSL评级为A，目前仍在保持更新。
加入开往，是为了能让我坚持写下去，记录自己的生活，记录当下，并在互联网上结识一群有趣的博友，发现更广阔的世界。

**Comment by alpaca-brother** [comment]
近期，网站正在进行ICP备案，需要暂时关闭一段时间，届时可能会出现无法访问的情况，敬请谅解。

**Comment by alpaca-brother** [comment]
网站已经备案成功，现在可以正常访问，希望可以尽快收录，谢谢。

**Comment by volfclub** [comment]
已收录
