### ISSUE TITLE
Zi_Gao的小站申请收录

### ISSUE THREAD

**Issue by Zi-Gao** [volfclub/travellings#38]
## 网站名称

Zi_Gao的小站

## 网站链接

https://zigao.tk/

## 徽标位置

侧栏

## 推荐理由

技术性博客，经验记录

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
