### ISSUE TITLE
听得入迷空间

### ISSUE THREAD

**Issue by urkey** [volfclub/travellings#381]
## 网站名称
听得入迷空间
## 网站链接
https://tdrme.cn/
## 徽标位置
主页头部
## 推荐理由
记录分享生活

**Comment by volfclub** [comment]
抱歉，没有找到开往

**Comment by urkey** [comment]
也许没有注意到，但是开往链接在主页最明显的位置



---原始邮件---
发件人: "逊狼"<notifications@github.com&gt;
发送时间: 2021年2月13日(周六) 晚上9:00
收件人: "volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送: "听得入迷"<2984107584@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [volfclub/travellings] 听得入迷空间 (#381)




 
抱歉，没有找到开往

**Comment by volfclub** [comment]
ok，注意到了，我指盯着顶啦了，抱歉

**Comment by urkey** [comment]
很高兴加入 开往

---原始邮件---
发件人: "逊狼"<notifications@github.com&gt;
发送时间: 2021年2月13日(周六) 晚上9:09
收件人: "volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送: "听得入迷"<2984107584@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [volfclub/travellings] 听得入迷空间 (#381)




 
ok，注意到了，我指盯着顶啦了，抱歉

**Comment by volfclub** [comment]
客气了，已收录

**Comment by urkey** [comment]
> 客气了，已收录

申请更改链接地址
原 `听得入迷空间  https://www.tdrme.cn/`
更改为https://blog.tdrme.cn/
开往链接转移到了导航栏（pc页面的顶部和手机页面的侧边栏）

**Comment by tdrme** [comment]
申请更改链接地址
原 听得入迷空间 https://www.tdrme.cn/
更改为https://blog.tdrme.cn/
开往链接转移到了导航栏（pc页面的顶部和手机页面的侧边栏）
