### ISSUE TITLE
Sakurai Kaede's Blog

### ISSUE THREAD

**Issue by sakuraikaede** [volfclub/travellings#382]
## 网站名称
Sakurai Kaede's Blog
## 网站链接
[https://sakurai.in](https://sakurai.in)
## 徽标位置
顶部
## 推荐理由
Personal Blog 可能有自己的文/技术相关

**Comment by sakuraikaede** [comment]
更正为侧栏

**Comment by volfclub** [comment]
文章似乎有些少，还是启用新站了？

**Comment by volfclub** [comment]
已收录
