### ISSUE TITLE
Magma Ink

### ISSUE THREAD

**Issue by MagmaBlock** [volfclub/travellings#384]
## 网站名称
Magma Ink
## 网站链接
https://magma.ink
## 徽标位置
顶栏、侧栏
## 推荐理由
个人博客/随笔，今年暑假开始建的网站 目前内容不是太多 正缓慢更新
主要内容为动漫、软件、生活向

**Comment by volfclub** [comment]
没有找到开往呢 ~

**Comment by MagmaBlock** [comment]
> 没有找到开往呢 ~

已添加，因为之前好几个月都没回复所以说暂时先下了

**Comment by volfclub** [comment]
已收录
