### ISSUE TITLE
建议设定几小时内随机跳转时排除去过的网站

### ISSUE THREAD

**Issue by zeruns** [volfclub/travellings#39]
可以通过cookie或ip识别同一个人，在跳转时识别这个人在几小时内已经跳转过哪些网站，排除这些网站，几小时后再加入回他的随机跳转列表，避免在短时间内都是随机抽到相同的网站（有的人运气就是这样），提高用户体验

**Comment by volfclub** [comment]
如果你擅长代码，可以 pull requests 。pull 之前先试试看。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
