### ISSUE TITLE
fly6022's Blog

### ISSUE THREAD

**Issue by fly6022** [volfclub/travellings#398]
## 网站名称

fly6022's Blog

## 网站链接

[https://fly6022.fun/](https://fly6022.fun)

## 徽标位置

首页侧边栏底部及“友情链接”页面单独板块

## 推荐理由

希望能够在互联网结识更多志同道合的好友。

**Comment by volfclub** [comment]
建议在侧栏相对靠上的位置放一个 travelling 外链
