### ISSUE TITLE
Emoticon网络表情数据包储存库

### ISSUE THREAD

**Issue by barkure** [volfclub/travellings#4]

**Comment by volfclub** [comment]
已收录，
建议将`Travelling`的外链移到页面上方，方便看到

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
link #3 ?

**Comment by HowieHz** [comment]
> 您好，[#3](https://github.com/travellings-link/travellings/issues/3) 和 [#4](https://github.com/travellings-link/travellings/issues/4) 都是我当时申请的，前者的链接现已恢复，后者的域名早已停止续费。

收到🤝
