### ISSUE TITLE
云游君的小站 申请收录

### ISSUE THREAD

**Issue by YunYouJun** [volfclub/travellings#40]
## 网站名称

云游君的小站

## 网站链接

<https://www.yunyoujun.cn>

## 徽标位置

侧栏与底部

## 推荐理由

有趣的想法。
希望能成为一个有趣的人。

**Comment by volfclub** [comment]
已收录

**Comment by YunYouJun** [comment]
已更新链接与图标。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
