### ISSUE TITLE
Jigsaw‘s Blog

### ISSUE THREAD

**Issue by Jigsaw111** [volfclub/travellings#404]
## 网站名称
Jigsaw's Blog
## 网站链接
https://blog.maddestroyer.xyz/
## 徽标位置
侧栏
## 推荐理由
也许会发现一些有用的东西（？）

**Comment by volfclub** [comment]
没有找到开往

**Comment by Jigsaw111** [comment]
![image](https://user-images.githubusercontent.com/50312681/107902869-80ffe500-6efc-11eb-87f7-1b1f9d5d7081.png)

**Comment by volfclub** [comment]
![image](https://user-images.githubusercontent.com/47265026/107906009-15b12400-6f8b-11eb-83a6-dae40c89026c.png)

**Comment by Jigsaw111** [comment]
> ![image](https://user-images.githubusercontent.com/47265026/107906009-15b12400-6f8b-11eb-83a6-dae40c89026c.png)
> 

我貌似用了纯白图标导致白天模式看不出来，明天起来就改。

**Comment by Jigsaw111** [comment]
> > ![image](https://user-images.githubusercontent.com/47265026/107906009-15b12400-6f8b-11eb-83a6-dae40c89026c.png)
> 
> 我貌似用了纯白图标导致白天模式看不出来，明天起来就改。

好了。

**Comment by volfclub** [comment]
我也不太清楚该怎么办，你放的位置还是不太符合新版的readme

**Comment by Jigsaw111** [comment]
确实，我的博客没有顶栏，我也不想自动展开侧栏。

**Comment by Jigsaw111** [comment]
要不就算了吧，你不用收录我的博客了。

**Comment by Jigsaw111** [comment]
谢谢。

**Comment by volfclub** [comment]
好的，欢迎有新的主题时来再次打开这个 issue
