### ISSUE TITLE
Mr.Chrosing`s Home博客申请收录

### ISSUE THREAD

**Issue by chrosing** [volfclub/travellings#41]
网站名称
Mr.Chrosing`s Home

网站链接
https://nasity.cn/

徽标位置
全页面的底部

推荐理由
我觉得这个想法很赞，值得推广下去。而且 希望加入的人越来越多

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/5cedab01-d915-47fb-887d-6095f970a7d9)

![Image](https://github.com/user-attachments/assets/578f1cee-4ca4-4137-8f4c-822b499f841c)
确认过期，已移除，欢迎重新申请！
