### ISSUE TITLE
Py的Blogggg

### ISSUE THREAD

**Issue by lzhbhlrPython** [volfclub/travellings#410]
## 网站链接：

- Vercel加速:https://myblog.lzhbhlrpython.vercel.app/
- Github原站:https://lzhbhlrpython.github.io/

（建议您添加vercel域名而非github域名）
## 徽标位置

顶部导航栏

## 推荐理由

这是一个学生狗的博客，希望大佬们多访问，多指点！

**Comment by volfclub** [comment]
内容有些少，要不再写写？
