### ISSUE TITLE
Eltrac's Track 申请收录

### ISSUE THREAD

**Issue by BigCoke233** [volfclub/travellings#42]
## 网站名称

Eltrac's Track

## 网站链接

https://guhub.cn

## 徽标位置

底部

## 推荐理由

很喜欢这个想法，想要参与进来。  
提了个 Pull Request 貌似没过 qwq

**Comment by volfclub** [comment]
建议顶部（可直接看到的地方）也加个外链。
我并不是很精通代码，抱歉了

**Comment by BigCoke233** [comment]
顶部导航栏加上了 qwq

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
