### ISSUE TITLE
因原作者无暇更新此项目，有一个提案

### ISSUE THREAD

**Issue by ssshooter** [volfclub/travellings#421]
- 因原作者无暇更新此项目，所以 fork 一份提高更新频率，地址在这里：https://github.com/ssshooter/travellings
- issue 需要直接提到 https://github.com/ssshooter/travellings
- 尚未添加到 volfclub/travellings 的朋友可以考虑先在这边添加，注意 fork 的开往请使用此地址：https://travellings-zeta.vercel.app/
- 原项目更新时此项目会同步更新

**Comment by vanfantasy2333** [comment]
您好，我这边看不到您那边的issue，您打开issue了嘛？

**Comment by ssshooter** [comment]
> 您好，我这边看不到您那边的issue，您打开issue了嘛？

欸，不好意思，打开了，没注意到 fork 之后默认关闭了

**Comment by Fachep** [comment]
您好，没见您更新呀？

**Comment by ssshooter** [comment]
> 您好，没见您更新呀？

因为没人在那边提 issue 😂

**Comment by Fachep** [comment]
> > 您好，没见您更新呀？
> 
> 因为没人在那边提 issue 😂

不是都八个issue了😒

**Comment by ssshooter** [comment]
> > > 您好，没见您更新呀？
> > 
> > 
> > 因为没人在那边提 issue 😂
> 
> 不是都八个issue了😒

😂 奇怪了没收到提醒，难道fork的仓库不带提醒

**Comment by ssshooter** [comment]
> > > 您好，没见您更新呀？
> > 
> > 
> > 因为没人在那边提 issue 😂
> 
> 不是都八个issue了😒

加好了，谢谢提醒 😂

**Comment by chengnan233** [comment]
@ssshooter 您好，问一下咱们fork这边和原项目是并不同步的吗，如果是的话或者说是fork这边不打理了，需不需要再去原项目重新提一下issue
