### ISSUE TITLE
韶坤博客

### ISSUE THREAD

**Issue by zzkuner** [volfclub/travellings#422]

**Comment by volfclub** [comment]
内容有些少，以及没找到开往

**Comment by zzkuner** [comment]
你好，这里有开往的链接啊







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "volfclub/travellings"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月14日(星期天) 下午3:24
收件人:&nbsp;"volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送:&nbsp;"张泽坤"<zzkuner@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [volfclub/travellings] 韶坤博客 (#422)





 
内容有些少，以及没找到开往

**Comment by volfclub** [comment]
1. 您的博客目前只有4篇文章，内容较少
2. 请将开往放到用户打开网页就能看到的地方

**Comment by zzkuner** [comment]
已修改，文章会不断更新，希望可以加入

**Comment by volfclub** [comment]
建议文章多写一些后来重新打开这个issue
