### ISSUE TITLE
yuaneuro的博客申请收录

### ISSUE THREAD

**Issue by yuaneuro** [volfclub/travellings#43]
## 网站名称
yuaneuro的博客
## 网站链接
https://yuaneuro.xyz
## 徽标位置
博客底部右侧
## 推荐理由
yuaneuro的小站是一个学习记录分享关于网络安全,python和技术的网站。记录学习的点滴,让每天都有新的收获。

**Comment by yuaneuro** [comment]
位置修改至左侧

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
