### ISSUE TITLE
源站错误

### ISSUE THREAD

**Issue by dyt5AAUI** [volfclub/travellings#431]
www.deepwave.top
报源站错误。
![image](https://user-images.githubusercontent.com/26762239/105802304-d3bd3f80-5fd5-11eb-84e6-63a90eac67b3.png)

**Comment by dyt5AAUI** [comment]
> [www.deepwave.top](http://www.deepwave.top)
> 报源站错误。
> ![image](https://user-images.githubusercontent.com/26762239/105802304-d3bd3f80-5fd5-11eb-84e6-63a90eac67b3.png)

**Comment by volfclub** [comment]
已处理
