### ISSUE TITLE
十二博客

### ISSUE THREAD

**Issue by shiertx** [volfclub/travellings#436]
## 网站名称

十二博客

## 网站链接

[https://blog.shiertx.com](https://blog.shiertx.com)

## 徽标位置

左侧边栏（PC/Pad端可直接看到）

## 推荐理由

~~凑个热闹~~

技术分享/生活杂谈

**Comment by volfclub** [comment]
已收录

**Comment by SHIERTX** [comment]
# 博客信息更新 / 域名更换

## 域名更换

原域名 blog.shiertx.com 新域名 licaoz.com

## 信息更新

### 网站名称

原名称 十二博客 新名称 李某人的部落格

### 徽标位置

在顶栏中，桌面端设备可以直接看到，移动端设备需要单击右上角展开后可见
