### ISSUE TITLE
缓归's Blog申请收录

### ISSUE THREAD

**Issue by haybin** [volfclub/travellings#44]
## 网站名称
缓归's Blog
## 网站链接
https://haybin.cn/
## 徽标位置
底部
## 推荐理由
很远的地方有一台冰冷的机器，储存着一个渺小人类渺小的热情，想有块属于自己的小地方储放自己的东西；即使来访的人很多，又或是人迹罕至，都没关系！希望能大家都可以一直运行下去

**Comment by volfclub** [comment]
建议顶部插入开往的外链

**Comment by haybin** [comment]
已经收录了吗

**Comment by haybin** [comment]
> 建议顶部插入开往的外链

现在是收录了吗

**Comment by volfclub** [comment]
还没，你可从这查看进度
https://github.com/volfclub/travellings/commits/master

**Comment by haybin** [comment]
> 还没，你可从这查看进度
> https://github.com/volfclub/travellings/commits/master

等一个好消息🙂

**Comment by volfclub** [comment]
建议在顶栏导航或其他直观的地方再放置一个开往的外链。
https://github.com/volfclub/travellings#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by haybin** [comment]
> 建议顶部插入开往的外链

只插入底部不能被收录吗😀

**Comment by volfclub** [comment]
不建议这么做。
放在一个明显的位置，以便友链接力下去。

**Comment by haybin** [comment]
> 不建议这么做。
> 放在一个明显的位置，以便友链接力下去。

如果是手机端访问，顶部导航栏是会隐藏的哈，无论PC和手机放在底部是最明显

**Comment by volfclub** [comment]
您可以看下 readme 里的例子，博客类推荐顶部或侧栏导航，加底部徽标。
事实上，目前只考虑了PC端。

**Comment by haybin** [comment]
> 您可以看下 readme 里的例子，博客类推荐顶部或侧栏导航，加底部徽标。
> 事实上，目前只考虑了PC端。

不能收录的话，我就取消底部链接了哈🙂

**Comment by volfclub** [comment]
好

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
