### ISSUE TITLE
更换域名

### ISSUE THREAD

**Issue by Zhou216** [volfclub/travellings#440]
之前的Zhou's Blog 域名已由https://zhoublog.xyz 更换为 https://idream.ink 请及时更改
谢谢！

**Comment by volfclub** [comment]
已处理

**Comment by yzqzss** [comment]
ID:[48]
域名再次更换： https://blog.dreamo.ink/
另外博客名称可更新为：『梦墨's Blog』

---
ref: https://github.com/saveweb/doing/issues/176
