### ISSUE TITLE
拾忆小站（重新申请）

### ISSUE THREAD

**Issue by July-Wind** [volfclub/travellings#441]
## 网站名称
拾忆小站

## 网站链接
https://www.syzhan.cn

## 徽标位置
顶栏

## 推荐理由
关注网络安全，分享前端知识。

**Comment by volfclub** [comment]
建议放在顶栏等打开就可以看到的地方

**Comment by July-Wind** [comment]
> 建议放在顶栏等打开就可以看到的地方

可以了

**Comment by volfclub** [comment]
已收录

**Comment by WhitemuTeam** [comment]
亲爱的@July-Wind，您好：
很抱歉打扰您，您站点上的开往链接有问题（https://travellings-zeta.vercel.app/），此站点不在官方镜像列表中，还请您更新开往链接：
https://travellings.link （推荐）
https://volfclub.github.io/travellings
https://travellings.pages.dev
https://travellings.netlify.com

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/832479bb-1ba9-4284-8c67-7a877e7bb3f3)
https://syzhan.cn/

![Image](https://github.com/user-attachments/assets/7c41113c-f0c2-4f48-80c7-7c1d1f945478)
https://www.syzhan.cn/

站点拥有主体似乎已经更换了？我们将移除您的站点，感谢您的支持，欢迎重新申请开往
