### ISSUE TITLE
7Wate 站点

### ISSUE THREAD

**Issue by 7Wate** [volfclub/travellings#445]
## 网站名称

7WATE`S Blog

## 网站链接

- 首页：[https://7wate.com/](https://7wate.com/)

- 博客：[https://blog.7wate.com/](https://blog.7wate.com/)

## 徽标位置

首页在关于页面最下图片链接（右上角菜单打开关于页面）

博客在下方菜单栏

## 推荐理由

Hahhh……

一个喜欢异想天开的家伙，看到后感觉找到了组织！

**Comment by volfclub** [comment]
抱歉，打开网页没有看到开往

**Comment by 7Wate** [comment]
晚上好，很抱歉打扰你。
站点首页在关于页面下拉尾部，博客的在菜单中第一个选项，因为实在找不到很合适的位置，所以很抱歉没能标注的清楚。
望加入开往，麻烦前辈了。


位置标注（红色方框）
















&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by 7Wate** [comment]
![image](https://user-images.githubusercontent.com/37507006/107875454-e2bf4f80-6efa-11eb-9ea6-e4b84c5b8420.png)
![image](https://user-images.githubusercontent.com/37507006/107875457-e81c9a00-6efa-11eb-9b45-51c4424c3d3e.png)

**Comment by volfclub** [comment]
直接放底栏吧和 © 2021 7Wate`s Blog. Using Typecho & Moricolor. 一行。
如果以后换主题，记得放顶栏。
已收录

**Comment by 7Wate** [comment]
已经在博客最底部添加徽标i✨，感谢您的回复！

**Comment by volfclub** [comment]
已收录
