### ISSUE TITLE
Sianx's Blog

### ISSUE THREAD

**Issue by L-20021213** [volfclub/travellings#446]
## 网站名称
Sianx's Blog
## 网站链接
https://blog.sianx.com/
## 徽标位置
导航栏最后一个
## 推荐理由
为了自己点击travellings看大佬网站方便hhhhh

**Comment by volfclub** [comment]
已收录

**Comment by HowieHz** [comment]
sianx.com 会重定向到 www.07ks.com。
确认过期，已删除，欢迎重新申请，
