### ISSUE TITLE
疑似不能正常访问的网站

### ISSUE THREAD

**Issue by Higurashi-kagome** [volfclub/travellings#448]
下列网站似乎不能够正常访问：

<details>
<summary>Links</summary>

https://blog.huixcwg.net/
https://userunknown.gq/
https://dpii.club/
https://blog.xiadengma.top/
https://jianchengwang.info/
https://www.deepwave.top/
https://mqaqm.com/
https://wp.remudaisuki.top/
https://blog.imoasis.cn/
https://blog.zigao.info/
https://blog.ajian.online/
https://sqdxwz.top/
https://blog.aenjoy.cn/
https://xiaowei.china97.cn/
https://www.y2jq.com/
https://blog.lu-sky.com/
https://uts.ski/
https://www.iibaofu.cn/
https://6773.ink/
https://blog.fkun.tech/
https://www.luxinzhangyun.top/
https://myheod.cn/
https://jishujun.com/
https://zhw150.top/
https://zzr3.xyz/
https://www.pootey.com/
https://vpsur.com/

</details>

**Comment by volfclub** [comment]
https://vpsur.com/
https://zzr3.xyz/
https://paperbox.xyz/
https://blog.lifeisgg.online/

根据您的反馈，处理了以上的网站。
其他的网站大多已处理，网站下线后 readme 的表格中序号会被“划删除线”，核心 js 文件里不会包含这些网址，不会跳到这些页面。

**Comment by Higurashi-kagome** [comment]
好的，谢谢。请问是否有考虑将不再能够正常访问的主页移出 README（或是另建文件保存）？因为随着时间的推移，划线的网站可能会越来越多，这将使 README 显得不那么整洁，另外，不再能够正常访问的网站对于阅读 README 的访问者来说可能并不重要。

**Comment by volfclub** [comment]
ok，我会考虑整理readme

**Comment by Higurashi-kagome** [comment]
Thanks.
