### ISSUE TITLE
疑似不满足收录条件的网站

### ISSUE THREAD

**Issue by Higurashi-kagome** [volfclub/travellings#449]
以下网站似乎不满足收录条件：

<details>
<summary>Links</summary>
<br>

包含侵入式广告：
https://blog.zeruns.tech/

无法进入主页（显示需要密码）：
https://lxxs.xyz/

</details>

**Comment by volfclub** [comment]
已处理 https://lxxs.xyz
另一个网站未发现明显的遮挡或悬窗广告

**Comment by Higurashi-kagome** [comment]
不知截图中的两个区域算不算，对于我来说，这已经算是十分明显的广告了：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/107894064-6021a900-6f69-11eb-9b8e-bd779ed8cdd1.png)

</details>

**Comment by volfclub** [comment]
我我认为非悬浮遮挡，广告内容也不是引人不适的就不算了，
毕竟现在网站都不太容易。

**Comment by Higurashi-kagome** [comment]
好的。
