### ISSUE TITLE
柠初文案馆请求收录

### ISSUE THREAD

**Issue by yixingla** [volfclub/travellings#45]
## 网站名称
柠初文案馆
## 网站链接
https://www.wenanguan.cn/
## 徽标位置
底部
## 推荐理由
让你难过的不是文案， 你明白的！

**Comment by volfclub** [comment]
建议顶部插入开往的外链

**Comment by volfclub** [comment]
建议在顶栏导航或其他直观的地方再放置一个开往的外链。
https://github.com/volfclub/travellings#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
