### ISSUE TITLE
Ender's Blog（重新申请）

### ISSUE THREAD

**Issue by code004Accepted** [volfclub/travellings#450]
> 要不再写写，以及没找到链接

_Originally posted by @volfclub in https://github.com/volfclub/travellings/issues/367#issuecomment-778611656_

---

由于博客更新的原因，之前的文章和新主题的配置文件未能及时更新，望谅解！

博客现已重新配置完毕，您可以在 https://ender.fun/ 上方菜单栏找到相应按钮，谢谢！

**Comment by volfclub** [comment]
已收录

**Comment by Matt-wzy** [comment]
![PnUJ8h.png](https://piccdn.freejishu.com/images/2021/04/18/PnUJ8h.png)
认真的么，整个网页就一个文章还说没时间写这都能录入么……我也想被录入*（（（（（
回头找到地方加链接就申请呢

**Comment by code004Accepted** [comment]
> ![PnUJ8h.png](https://camo.githubusercontent.com/93abd1692bfa1599b05c4965789ee2781232568a46ba10a805efca3a7f0ecdbd/68747470733a2f2f70696363646e2e667265656a697368752e636f6d2f696d616765732f323032312f30342f31382f506e554a38682e706e67)
> ~认真的么，整个网页就一个文章还说没时间写这都能录入么……我也想被录入*（（（（（~
> ~回头找到地方加链接就申请呢~
> 啊仔细看了看楼主是个有故事的高中生和之前的网站，啊不好意思鄙人不才打扰了……
> 不得不说现在年轻人真的是太厉害了（（（高中就这么有成就（（（（（（（

您好，是这样的，之前一共写过六十余篇文章，如果算上之前放入博客但后来因为版权问题删除（因为我在一个OJ上同步发表了这些题解，但后来被告知不允许同步在自己的博客发表相同内容）的一些信息学题解的话至少有个八九十篇

近期因为各种原因，坦诚地说有学业成绩下滑、新入高中需要建立人际关系、自己的MC服务器缺乏管理和学校不断给信竞生布置大量额外任务等等原因。希望包括您在内的所有读者理解。此外，一来近期很少有机会用自己的笔记本写作，二来众所周知的原因比较难上GitHub，所以文章迟迟未更新

那么趁着今晚有时间我就更一篇呗233，谢谢您的提醒。

另外，您可以在OI圈找到数以千计的初中拿到世界级比赛大奖的学生，并且您大可不必为了一个博客是否被收录一事而发布大量并不让人感觉友好的言论。

**Comment by code004Accepted** [comment]
> ![PnUJ8h.png](https://camo.githubusercontent.com/93abd1692bfa1599b05c4965789ee2781232568a46ba10a805efca3a7f0ecdbd/68747470733a2f2f70696363646e2e667265656a697368752e636f6d2f696d616765732f323032312f30342f31382f506e554a38682e706e67)
> ~认真的么，整个网页就一个文章还说没时间写这都能录入么……我也想被录入*（（（（（~
> ~回头找到地方加链接就申请呢~
> 啊仔细看了看楼主是个有故事的高中生和之前的网站，啊不好意思鄙人不才打扰了……
> 不得不说现在年轻人真的是太厉害了（（（高中就这么有成就（（（（（（（

您好，是这样的，之前一共写过六十余篇文章，如果算上之前放入博客但后来因为版权问题删除（因为我在一个OJ上同步发表了这些题解，但后来被告知不允许同步在自己的博客发表相同内容）的一些信息学题解的话至少有个八九十篇

近期因为各种原因，坦诚地说有学业成绩下滑、新入高中需要建立人际关系、自己的MC服务器缺乏管理和学校不断给信竞生布置大量额外任务等等原因。希望包括您在内的所有读者理解。此外，一来近期很少有机会用自己的笔记本写作，二来众所周知的原因比较难上GitHub，所以文章迟迟未更新

那么趁着今晚有时间我就更一篇呗233，谢谢您的提醒。

另外，您可以在OI圈找到数以千计的初中拿到世界级比赛大奖的学生，并且您大可不必为了一个博客是否被收录一事而发布大量并不让人感觉友好的言论。

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
