### ISSUE TITLE
BlueSky01st's Blog

### ISSUE THREAD

**Issue by BlueSky01st** [volfclub/travellings#451]
## 网站名称
BlueSky01st's BLog
## 网站链接
[https://bluesky01st.js.org](https://bluesky01st.js.org)
## 徽标位置
页中及底栏(⚠ 打开网页后能直接看到)
## 推荐理由
分享知识及感想

**Comment by volfclub** [comment]
建议放在顶部，打开网页就能看到的地方

**Comment by BlueSky01st** [comment]
![图片](https://user-images.githubusercontent.com/57856874/107871808-d7aaf600-6edf-11eb-8d8c-467de7369d46.png)
这样可以吗?

**Comment by volfclub** [comment]
可以的，但你的内容似乎也有点少，要不再写写然后来申请下？

**Comment by BlueSky01st** [comment]
好的，谢谢
