### ISSUE TITLE
余生‘s Blog（重新申请）

### ISSUE THREAD

**Issue by yszww** [volfclub/travellings#452]
之前那个博客已撤销另换，现重新申请。
名称:余生 ' Blog
地址:https://www.ysazw.cn/
头像:https://www.ysazw.cn/favicon.ico
描述:足够优秀才有谈资。
添加位置：底部。

**Comment by volfclub** [comment]
建议放在顶部，打开网页就能看到的地方

**Comment by yszww** [comment]
底部可以审核通过吗  如果必须顶部我再改

**Comment by volfclub** [comment]
要求是放在pc打开网页能看到的地方即可

**Comment by yszww** [comment]
底部也能看到的  在底部呈现logo形式更美观  顶部单纯文字 不尽美观

**Comment by volfclub** [comment]
建议参考下已收录的网站

**Comment by yszww** [comment]
okok  顶部已额外添加

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
