### ISSUE TITLE
秉性之松（重新申请）

### ISSUE THREAD

**Issue by wibus-wee** [volfclub/travellings#453]
## 网站名称
秉性之松

## 网站链接
https://blog.iucky.cn

## 徽标位置
网站底部以及顶部右侧

## 推荐理由
持续更新的个人博客～

上次是因为我服务器在编译内容所导致的暂歇性无法访问，抱歉

**Comment by volfclub** [comment]
请放在顶栏，或其他可以直接看到的地方

**Comment by wibus-wee** [comment]
已添加至顶部右侧

**Comment by volfclub** [comment]
已收录
