### ISSUE TITLE
重新申请 小陈网管的小窝

### ISSUE THREAD

**Issue by BLxcwg666** [volfclub/travellings#455]
## 网站名称
小陈网管的小窝

## 网站网址
https://blog.xcbili.cn

## 徽标位置
网站左侧和最底部

## 推荐理由
每周稳定更新一些计算机技术知识，网站已启用HTTPS和HSTS，MySSL评级为A+
之前blog.huixcwg.net的域名已停用，故以申请此域名

**Comment by volfclub** [comment]
已经处理了 https://github.com/volfclub/travellings/issues/396
