### ISSUE TITLE
吴李曾

### ISSUE THREAD

**Issue by unluckynike** [volfclub/travellings#456]
网站名称
吴李曾

网站链接
https://www.wulinzeng.vip/

徽标位置
底栏（⚠ 打开网页后能直接看到）

推荐理由
分享学习编程历程，热爱生活。

**Comment by volfclub** [comment]
请在顶栏放一个开往的外链吧

**Comment by unluckynike** [comment]
okk 可以了，放在顶部导航栏里了

**Comment by volfclub** [comment]
已收录，
您似乎在用 Font Awesome ，推荐 fa-subway
