### ISSUE TITLE
MZRME'S请求收录

### ISSUE THREAD

**Issue by lzbz** [volfclub/travellings#46]
## 网站名称
MZRME'S
## 网站链接
https://mzrme.com
## 徽标位置
导航栏
## 推荐理由
You're the Miracles.

**Comment by volfclub** [comment]
建议顶部插入开往的外链

**Comment by volfclub** [comment]
文章似乎有些少？

**Comment by lzbz** [comment]
> 文章似乎有些少？

最早在三年前，服务器到期没取回，然后最近数据库出了问题，数据全没了

**Comment by volfclub** [comment]
😥建议文章有两页时再来申请一次？

**Comment by lzbz** [comment]
好吧



在 2020-03-29 09:22:29，"逊狼" <notifications@github.com> 写道：

😥建议文章有两页时再来申请一次？

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
