### ISSUE TITLE
当神奇降临

### ISSUE THREAD

**Issue by Magic-mystic** [volfclub/travellings#462]
## 网站名称
当神奇降临
（💡 会在 Readme 中展示给大家）

## 网站网址
https://blog.toutop.cn
（💡 必须是 https 网站）

## 徽标位置
侧栏
（💡 只放在“网页底部”，或只放在“默认收起的菜单里”，审核通过率较低；
核心要求是放在 PC 打开网页后能**直接看到的地方**——一般而言，顶栏或固定的侧栏是不错的选择，具体示例可参见 Readme 或已收录的网站）

## 推荐理由
记录互联网中遇到的一点一滴
（💡 不会展示在 Readme）

**Comment by volfclub** [comment]
已收录
