### ISSUE TITLE
凌维三度

### ISSUE THREAD

**Issue by weclont** [volfclub/travellings#463]
## 网站名称
凌维三度

## 网站网址
https://www.fwder.cn

## 徽标位置
顶栏

## 推荐理由
分享我的学习生活点点滴滴

**Comment by volfclub** [comment]
浅色的方形图片已放到 assets 文件夹中，
已收录

**Comment by weclont** [comment]
已经更新域名。
## 网站名称
凌维三度

## 网站网址
https://blog.fwder.cn/

## 徽标位置
左侧栏


## 内容方向
技术开发内容以及各种原创教程
