### ISSUE TITLE
御坂の地下室

### ISSUE THREAD

**Issue by zxy678** [volfclub/travellings#466]
## 网站名称
御坂の地下室

## 网站网址
https://misakaloli.com

## 徽标位置
底部&顶栏

## 推荐理由
分享个人生活与经验

**Comment by volfclub** [comment]
已收录

**Comment by HowieHz** [comment]
link #731

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/93acae72-1436-4b7f-8c8d-8ca04ef3e05b)
bot 被人机验证拦下来了，导致巡查未检查到开往外链

**Comment by zxy678** [comment]
> ![Image](https://github.com/user-attachments/assets/93acae72-1436-4b7f-8c8d-8ca04ef3e05b) bot 被人机验证拦下来了，导致巡查未检查到开往外链

已将Travellings的UA添加至人机验证排除列表，将在稍后生效 ;-)
