### ISSUE TITLE
Hicool嗨酷

### ISSUE THREAD

**Issue by latastic** [volfclub/travellings#467]
## 网站名称
Hicool嗨酷

## 网站网址
   https://www.hicool.icu

## 徽标位置
底栏（⚠ 打开网页后能直接看到）

## 推荐理由
个人的小博客，希望和大家交朋友

**Comment by volfclub** [comment]
嗯……你放到那里了呢？

**Comment by latastic** [comment]
啊……抱歉抱歉 换了个主题忘加了 马上加上 真的抱歉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "volfclub/travellings"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月23日(星期二) 晚上9:25
收件人:&nbsp;"volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送:&nbsp;"御坂539号"<wangyunkai1234567@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [volfclub/travellings] Hicool嗨酷 (#467)





 
嗯……你放到那里了呢？

**Comment by latastic** [comment]
> 嗯……你放到那里了呢？

抱歉昨天换主题了 刚刚加好了

**Comment by volfclub** [comment]
请参见新版的readme，放在顶栏导航一个开往就可以了
