### ISSUE TITLE
小姜饼请求收录

### ISSUE THREAD

**Issue by Dogou** [volfclub/travellings#47]
## 网站名称
姜饼の小窝
## 网站链接
https://blog.jambing.cn
## 徽标位置
底部
## 推荐理由
这是一个新的开始，文章少是因为之前删库重来了。

**Comment by volfclub** [comment]
建议在顶栏导航或其他直观的地方再放置一个开往的外链。
https://github.com/volfclub/travellings#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by volfclub** [comment]
内容有些少？

**Comment by volfclub** [comment]
建议文章有两页时再来申请一次？
