### ISSUE TITLE
沐风の秘密基地

### ISSUE THREAD

**Issue by mufeng233** [volfclub/travellings#471]
## 网站名称
沐风の秘密基地

## 网站网址
https://mf.xgzwlkj.cn

## 徽标位置
侧栏

## 推荐理由
分享一些小技术！

**Comment by volfclub** [comment]
网页打不开了呀，我看到百页了

**Comment by mufeng233** [comment]
可能是wp插件自动更新出了一些问题，我正在解决



发自vivo智能手机

**Comment by mufeng233** [comment]
> 网页打不开了呀，我看到百页了

麻烦重新看一下，已经好了，
