### ISSUE TITLE
10082009's blog

### ISSUE THREAD

**Issue by jack10082009** [volfclub/travellings#475]
## 网站名称
10082009's blog

## 网站网址
[https://10082009.com](https://10082009.com)

## 徽标位置
侧栏（⚠ 打开网页后能直接看到）

## 推荐理由
加入开往

**Comment by volfclub** [comment]
建议放顶栏更好

**Comment by jack10082009** [comment]
顶栏的项目已经够多啦，看看再建议一个其他的位置吧
