### ISSUE TITLE
GATESX博客

### ISSUE THREAD

**Issue by GATESX** [volfclub/travellings#480]
## 网站名称
GATESX博客

## 网站网址
https://www.gatesx.cn

## 徽标位置
侧栏（我使用了cf加速）

## 推荐理由
个人博客,资源分享,技术分享,生活记录,网络世界,线路解析

**Comment by volfclub** [comment]
抱歉，没有找到

**Comment by GATESX** [comment]
![87BC1A99-BE3B-4545-B8DD-3E08F11DA746](https://user-images.githubusercontent.com/69007809/113476836-93d07800-94b0-11eb-848c-337c30a3aa96.png)
左侧开往就是了（我改成now.sh吧）

**Comment by GATESX** [comment]
我加一个"接力"吧

**Comment by GATESX** [comment]
因为我的网站自动加载新的文章.如果放在底部很难看到

**Comment by volfclub** [comment]
已收录
