### ISSUE TITLE
GOOPHER’s blog

### ISSUE THREAD

**Issue by Goopher97** [volfclub/travellings#485]
## 网站名称
GOOPHER’s Blog
## 网站网址
https://goopher.tk
## 徽标位置
顶栏
## 推荐理由
知识分享

**Comment by volfclub** [comment]
抱歉，没有找到

**Comment by Goopher97** [comment]
请问是网站打不开还是找不到前往按钮?按钮就在顶栏上,PC和手机端截图  ![](https://cdn.jsdelivr.net/gh/Goopher97/tuchuang2@master/img/QQ20210403-193136@2x.png) 
![](https://cdn.jsdelivr.net/gh/Goopher97/tuchuang2@master/img/QQ20210403-193110@2x.png)

**Comment by Goopher97** [comment]
这个按钮差不多挂了一个月了,如果不收录的话那我就去掉了

**Comment by volfclub** [comment]
没什么问题，回错 issue 了，抱歉。
已收录。
