### ISSUE TITLE
请求收录

### ISSUE THREAD

**Issue by L-20021213** [volfclub/travellings#49]
## 网站名称
Smilear's Blog
## 网站链接
https://smilear.cn/
## 徽标位置
右侧广告栏
## 推荐理由
技术博客，目前有点像资源网，后面会改

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
