### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by voidoath** [volfclub/travellings#50]
## 网站名称
krau'blog
## 网站链接
https://krau.top
## 徽标位置
顶部栏右侧
## 推荐理由
日常生活分享，技术学习交流

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by krau** [comment]
收到，已更新地址。博主的 github 账号已变更为此账号( @krau )，原先的账号已弃用。
