### ISSUE TITLE
悲催の记事账簿

### ISSUE THREAD

**Issue by Shizuri23** [volfclub/travellings#501]
## 网站名称
悲催の记事账簿

## 网站网址
https://nmsl.pet

## 徽标位置
顶栏

## 推荐理由
热爱二次元，热爱各种游戏

**Comment by volfclub** [comment]
内容有些少要不再写写

**Comment by Shizuri23** [comment]
那是当然的（之前博客炸了，目前正在爆肝中）

**Comment by Shizuri23** [comment]
> 内容有些少要不再写写

那是当然的（之前博客炸了，目前正在爆肝中）

**Comment by volfclub** [comment]
> 
> 
> > 内容有些少要不再写写
> 
> 那是当然的（之前博客炸了，目前正在爆肝中）

好的，欢迎较多后来回复下
