### ISSUE TITLE
JsOnGmAX-博客 （变更网址）

### ISSUE THREAD

**Issue by jsongmax** [volfclub/travellings#513]
## 网站名称
JsOnGmAX-博客

## 网站网址
原：https://jsong.cn
申请变更为：
现：https://jsongx.com

## 徽标位置
左侧导航栏

## 推荐理由
分享当前实用技术，安全信息，技术交路

**Comment by volfclub** [comment]
已处理

**Comment by HowieHz** [comment]
link #226
