### ISSUE TITLE
抱歉，退圈了…

### ISSUE THREAD

**Issue by alpaca-brother** [volfclub/travellings#514]
本人高二学生，已经进入一轮复习，目前无力维护站点，已关闭站点，申请退出。

**Comment by ChrisKimZHT** [comment]
> 本人高二学生，已经进入一轮复习，目前无力维护站点，已关闭站点，申请退出。

哈，不至于。我高三了，网站还开着，顶多基本不更新了罢了。

**Comment by alpaca-brother** [comment]
抱歉，当我没说，现在继续浪……

**Comment by ljcbaby** [comment]
> > 本人高二学生，已经进入一轮复习，目前无力维护站点，已关闭站点，申请退出。
> 
> 哈，不至于。我高三了，网站还开着，顶多基本不更新了罢了。

同高三，就是挂着不更新了而已
