### ISSUE TITLE
Tangxs's Tavern

### ISSUE THREAD

**Issue by tangxs0808** [volfclub/travellings#517]
## Tangxs's Tavern
（💡 会在 Readme 中展示给大家）

## https://boke.tangxscloud.top
（💡 必须是 https 网站）

## 顶栏
（💡 只放在“网页底部”，或只放在“默认收起的菜单里”，审核通过率较低；
核心要求是放在 PC 打开网页后能**直接看到的地方**——一般而言，顶栏或固定的侧栏是不错的选择，具体示例可参见 Readme 或已收录的网站）

## 希望每个人都能搭上 “开往”这趟列车
（💡 不会展示在 Readme）

**Comment by volfclub** [comment]
![图片](https://user-images.githubusercontent.com/47265026/113478494-abf9c480-94bb-11eb-9040-41149de0ef19.png)
网站打不开呀

**Comment by tangxs0808** [comment]
可以打开

**Comment by volfclub** [comment]
网址打不开
