### ISSUE TITLE
云梦 ╮不浅の部落阁

### ISSUE THREAD

**Issue by ADworld233** [volfclub/travellings#519]
## 网站名称:云梦 ╮不浅の部落阁
（💡 会在 Readme 中展示给大家）

## 网站网址:https://blog.adworld.top/
（💡 必须是 https 网站）

## 徽标位置:顶部（导航栏放链接），底部或将插入徽标！
（💡 只放在“网页底部”，或只放在“默认收起的菜单里”，审核通过率较低；
核心要求是放在 PC 打开网页后能**直接看到的地方**——一般而言，顶栏或固定的侧栏是不错的选择，具体示例可参见 Readme 或已收录的网站）

## 推荐理由:梦，开始的地方
（💡 不会展示在 Readme）

**Comment by volfclub** [comment]
![图片](https://user-images.githubusercontent.com/47265026/113478423-56bdb300-94bb-11eb-817e-d2f35aa69057.png)
网站没有正常加载

**Comment by ADworld233** [comment]
非常抱歉，我们这出了些小状况，感谢提醒！我们会尽快解决并重交申请


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "volfclub/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月3日(星期六) 晚上8:30
***@***.***&gt;;
抄送:&nbsp;"云梦 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [volfclub/travellings] 云梦 ╮不浅の部落阁 (#519)





 

 网站没有正常加载

**Comment by volfclub** [comment]
![图片](https://user-images.githubusercontent.com/47265026/113478946-8b7f3980-94be-11eb-94af-69e8dffc2de4.png)
你的网站访问起来似乎不是很顺畅

**Comment by ADworld233** [comment]
延时是有些大，海外机子，似乎需要一些时间载入适配，不过一般还行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "volfclub/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月3日(星期六) 晚上8:53
***@***.***&gt;;
抄送:&nbsp;"云梦 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [volfclub/travellings] 云梦 ╮不浅の部落阁 (#519)





 

 你的网站访问起来似乎不是很顺畅

**Comment by ADworld233** [comment]
我尽量做优化的！

**Comment by ADworld233** [comment]
> ![图片](https://user-images.githubusercontent.com/47265026/113478946-8b7f3980-94be-11eb-94af-69e8dffc2de4.png)
> 你的网站访问起来似乎不是很顺畅

目前网站速度通过优化有许提升，您看可以嘛
