### ISSUE TITLE
yanliang's blog 请求收录

### ISSUE THREAD

**Issue by gyl-coder** [volfclub/travellings#52]
## 网站名称

yanliang's blog

## 网站链接

https://gyl-coder.top

## 徽标位置

顶部导航栏

## 推荐理由

技术博客

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
