### ISSUE TITLE
阿苏可の小博客

### ISSUE THREAD

**Issue by iasuke** [volfclub/travellings#521]
## 阿苏可の小博客
（💡 会在 Readme 中展示给大家）

## https://asuko.icu
（💡 必须是 https 网站）

## 左侧菜单项和友链里面
（💡 只放在“网页底部”，或只放在“默认收起的菜单里”，审核通过率较低；
核心要求是放在 PC 打开网页后能**直接看到的地方**——一般而言，顶栏或固定的侧栏是不错的选择，具体示例可参见 Readme 或已收录的网站）

## 推荐理由
热爱二次元, 平时写点自己想写的。

**Comment by volfclub** [comment]
已收录
