### ISSUE TITLE
Nymane's Blog请求收录

### ISSUE THREAD

**Issue by Nymane** [volfclub/travellings#53]
## 网站名称
Nymane's Blog

## 网站链接
https://www.nymane.xyz
## 徽标位置
左侧
## 推荐理由
想通过travellings看到更多人的同时，也想让更多人看到我

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
