### ISSUE TITLE
TIR: Today I Read, 社区驱动的高质量阅读列表

### ISSUE THREAD

**Issue by jwenjian** [volfclub/travellings#535]
## 网站名称
TIR: Today I Read, 社区驱动的高质量阅读列表

## 网站网址
https://tir.cool

## 徽标位置
顶栏

## 推荐理由
每天分享及时的高质量科技、开源、编程、科学新闻，推荐有趣有用的网站、工具

**Comment by volfclub** [comment]
已收录
