### ISSUE TITLE
Sakura_Team

### ISSUE THREAD

**Issue by shanshatest** [volfclub/travellings#538]
## 网站名称
Sakura_Team - 探索未来

## 网站网址
https://sakurasep.club/

## 徽标位置
放在导航栏，可以直接看到。

## 推荐理由
希望我们所写的内容，可以帮助每一个需要的人。

**Comment by shanshatest** [comment]
你好，已经对指向的域名进行了更改

**Comment by volfclub** [comment]
已收录
