### ISSUE TITLE
ajian博客请求收录

### ISSUE THREAD

**Issue by ajian2002** [volfclub/travellings#55]

**Comment by volfclub** [comment]
建议顶部或其他可以直接看到的地方再加一个外链

**Comment by ajian2002** [comment]
> 建议顶部或其他可以直接看到的地方再加一个外链

顶栏，页脚已添加

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by yegetables** [comment]
> 您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：
> 
> gif动图：https://www.travellings.cn/assets/logo.gif svg：https://www.travellings.cn/assets/logo.svg
> 
> 请您及时更换相关地址，谢谢配合。

已更新

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已移除开往链接，现已将您移除，如需加入开往，可再次按照流程申请。 疑似被挂马。 @yegetables
