### ISSUE TITLE
冻符「Minus-K」

### ISSUE THREAD

**Issue by kawashiro-ryofu** [volfclub/travellings#556]
## 网站名称
冻符「Minus-K」

## 网站网址
https://www.kawashiros.club/

## 徽标位置
导航栏

## 推荐理由
一切都是命运石之门的选择

**Comment by kawashiro-ryofu** [comment]
更新完成，目前跳转至 [https://travellings.link](https://travellings.link)。

等待收录……

**Comment by volfclub** [comment]
已收录
