### ISSUE TITLE
freejishu的美丽世界 申请收录

### ISSUE THREAD

**Issue by freejishu** [volfclub/travellings#57]
## 网站名称

freejishu的美丽世界

## 网站链接

https://www.freejishu.com

## 徽标位置

左侧抽屉、右侧抽屉、页底（无自动延展）

## 推荐理由

做Blog好几年了，希望能交更多的朋友，传递更多的快乐^.^

**Comment by volfclub** [comment]
已收录

**Comment by freejishu** [comment]
已经完成更改。closed。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by freejishu** [comment]
经检查，3处（左侧菜单、右侧工具栏、底部）已经全部更换。closed。
