### ISSUE TITLE
小太の游乐园 申请收录

### ISSUE THREAD

**Issue by SatoSouta** [volfclub/travellings#58]
## 网站名称
小太の游乐园
## 网站链接
https://713.moe/
## 徽标位置
左侧抽屉
## 推荐理由
小伙伴们互相串门~

**Comment by volfclub** [comment]
考虑底部放一个徽标吧

**Comment by SatoSouta** [comment]
> 考虑底部放一个徽标吧

ok了~

**Comment by volfclub** [comment]
已收录

**Comment by SatoSouta** [comment]
已完成更改，摆放位置由侧栏抽屉换为顶部导航

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by SatoSouta** [comment]
链接地址已修改

**Comment by Veitzn1** [comment]
您的站点https://baka.fun 还未正确部署开往图标和链接，Blog无法访问哟～
