### ISSUE TITLE
ChrisKim's Blog 站点更改

### ISSUE THREAD

**Issue by ChrisKimZHT** [volfclub/travellings#587]
近期站点备案成功，站点有更改
站点名称更改为：
“颢天图文”
域名更改为：
“https://www.zouht.com”

**Comment by volfclub** [comment]
已修改

**Comment by ChrisKimZHT** [comment]
> 已修改

列表里信息似乎还没有更改诶？仍然是我的旧域名。
另外，链接我已经修改好啦。

**Comment by volfclub** [comment]
等下更新，今日先休息了，安
