### ISSUE TITLE
kirito41dd的博客

### ISSUE THREAD

**Issue by kirito41dd** [volfclub/travellings#588]
## 网站名称
kirito41dd's blog

## 网站网址
https://www.kirito41dd.cn

## 徽标位置
顶栏

## 推荐理由
编程，技术，被带歪也不能怨我

**Comment by volfclub** [comment]
已收录

**Comment by kirito41dd** [comment]
被机器人踢醒了，顺便能忙换下域名么，谢谢。 旧域名的302可以验证是同一个人

https://www.kirito.info/
