### ISSUE TITLE
悲催の记事账簿

### ISSUE THREAD

**Issue by Shizuri23** [volfclub/travellings#589]
## 网站名称
 悲催の记事账簿

## 网站网址
https://nmsl.pet/

## 徽标位置
左边侧栏

## 推荐理由
分享各种有意思的东西，分享自己的想法

**Comment by Shizuri23** [comment]
> https://travellings.link

已更改

**Comment by volfclub** [comment]
你目前只有6篇文章，要不再写写看？

**Comment by Shizuri23** [comment]
> 你目前只有6篇文章，要不再写写看？

之前博客被攻击了，目前正在慢慢添加文章

**Comment by volfclub** [comment]
好的，欢迎文章恢复后再来恢复下这个 issue

**Comment by Shizuri23** [comment]
> 好的，欢迎文章恢复后再来恢复下这个 issue

好的
