### ISSUE TITLE
RS-Nocsi--博客论坛站点链接更改

### ISSUE THREAD

**Issue by RS-Nocsi** [volfclub/travellings#590]
我是RS-Nocsi--博客论坛的站长，博客的站点链接更改为：[https://www.rsnocsi.cn/](https://www.rsnocsi.cn/)，其它保持不变，谢谢！

**Comment by volfclub** [comment]
您好，由于网络原因，请修改下开往指向的网址 https://github.com/volfclub/travellings#2-%E5%B0%86%E5%BC%80%E5%BE%80%E6%94%BE%E5%88%B0%E6%82%A8%E7%BD%91%E9%A1%B5%E6%89%93%E5%BC%80%E5%90%8E%E5%B0%B1%E8%83%BD%E7%9C%8B%E5%88%B0%E7%9A%84%E5%9C%B0%E6%96%B9%E8%AE%A9%E5%8F%8B%E9%93%BE%E6%8E%A5%E5%8A%9B%E4%B8%8B%E5%8E%BB

**Comment by RS-Nocsi** [comment]
已经修改

**Comment by volfclub** [comment]
已处理

**Comment by HowieHz** [comment]
link #494
