### ISSUE TITLE
Funix‘s blog(https://www.funix.cn)的站长申请修改信息

### ISSUE THREAD

**Issue by ImVeri** [volfclub/travellings#592]
## 网站名称

由 **Funix‘s blog** 更改为： **56Kb/s**

## 网站链接

保持不变

## 徽标位置

**顶栏**

![Screenshot_20210618_233053](https://user-images.githubusercontent.com/49151698/122584753-4e721e80-d08d-11eb-9835-411d07cdcbc9.png)

**Comment by volfclub** [comment]
已处理
