### ISSUE TITLE
guole's Blog

### ISSUE THREAD

**Issue by kuole-o** [volfclub/travellings#593]
## 网站名称
guole's Blog

## 网站网址
https://guole.fun/

## 徽标位置
菜单栏顶栏右侧

## 推荐理由
希望借此多认识些志同道合的网友，一切交流，研究一些好玩的 有趣的东西

**Comment by volfclub** [comment]
抱歉，没有找到

**Comment by kuole-o** [comment]
> 抱歉，没有找到

不好意思 我确实添加了近半个月，后来发现申请一直没回应，以为项目没有维护了，就去掉了。我关掉这个，等再次更新添加后，再来申请
