### ISSUE TITLE
INSPI请求收录

### ISSUE THREAD

**Issue by arect** [volfclub/travellings#6]

**Comment by volfclub** [comment]
已收录，
建议将开往放在可直接看到的地方

**Comment by inspiration2030** [comment]
> 已收录，
> 建议将开往放在可直接看到的地方

已经在左右侧栏和页尾加入链接。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
