### ISSUE TITLE
Scvoet

### ISSUE THREAD

**Issue by kecrily** [volfclub/travellings#60]

**Comment by volfclub** [comment]
🐱‍💻只有3篇内容吗，建议8篇内容后再来申请一次？

**Comment by scvoet** [comment]
@volfclub 遗憾的是我学不会「水文」这个技能，也没有打算恢复数据。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
