### ISSUE TITLE
异端-人人都是艺术家

### ISSUE THREAD

**Issue by hillvision** [volfclub/travellings#606]
## 网站名称
异端 - 人人都是艺术家

## 网站网址
https://here.sy

## 徽标位置
网站顶栏，手机侧栏

## 推荐理由
“人人都是艺术家”主要收集互联网精彩文章，为不同口味的读者准备了不同风格的文章、图片。除了搞笑类，还有讽刺类、哲理类、感性类、爱情类等文章图片视频任君挑选。

**Comment by volfclub** [comment]
重复
