### ISSUE TITLE
网站失效

### ISSUE THREAD

**Issue by garryde** [volfclub/travellings#616]
https://www.yamdr.cn/

**Comment by yzqzss** [comment]
![图片](https://user-images.githubusercontent.com/30341059/127735637-a491d8dc-b461-411a-b218-96d1dbf0796c.png)

补充："开往"链接还在，只是博主引用的ico404了。

---
@Yamdr

**Comment by Yamdr** [comment]
已调整图片链接地址，感谢提醒

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："yzqzss ***@***.***&gt;;
发送时间：2021年7月31日(星期六) 下午5:35
收件人："volfclub/travellings" ***@***.***&gt;;
抄送："Yamdr ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [volfclub/travellings] 网站失效 (#616)
-----------------------------------

 

 

 
补充："开往"链接还在，只是博主引用的ico404了。
 
 
@Yamdr

**Comment by volfclub** [comment]
感谢提醒
