### ISSUE TITLE
希望老板能抽时间清理一下

### ISSUE THREAD

**Issue by ScarletDor** [volfclub/travellings#619]
今天点开了许多开往的站点，有的没有开往链接，有的网站打不开了。虽然站点太多维护很累，但是希望能抽出时间清理一下，也对此有个好环境！感谢

**Comment by ljcbaby** [comment]
我觉得可以转成团队，合作维护

**Comment by zc998800** [comment]
> 我觉得可以转成团队，合作维护

看到邮件我还以为收录了呢噗

其实来一套代码检测首页链接是否存在开往就好了

**Comment by ljcbaby** [comment]
纯文本的检测也不行，可以网页代码里有但不显示的

**Comment by LEORChn** [comment]
> 
> 
> 纯文本的检测也不行，可以网页代码里有但不显示的

能不能行，这就要看个人前端技术水平如何了。

**Comment by LikeJson** [comment]
> > 纯文本的检测也不行，可以网页代码里有但不显示的
> 
> 能不能行，这就要看个人前端技术水平如何了。

看 body 有没有东西就行了吧

**Comment by LikeJson** [comment]
顺便上报一个 挂了的网站 https://www.heson10.com/

**Comment by WhitemuTeam** [comment]
> 顺便上报一个 挂了的网站 https://www.heson10.com/

这个没挂掉，我可以访问（没开加速器），应该是您网络原因

**Comment by ljcbaby** [comment]
我这边也能访问




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月21日(星期六) 晚上10:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [volfclub/travellings] 希望老板能抽时间清理一下 (#619)





  
顺便上报一个 挂了的网站 https://www.heson10.com/
  
这个没挂掉，我可以访问（没开加速器），应该是您网络原因
 
&mdash;
