### ISSUE TITLE
CORE 申请收录

### ISSUE THREAD

**Issue by kotoyuuko** [volfclub/travellings#62]
## 网站名称

CORE

## 网站链接

[core.moe](https://core.moe)

## 徽标位置

底部

## 推荐理由

个人原创博客

**Comment by volfclub** [comment]
建议在顶部导航插入一个外链

**Comment by kotoyuuko** [comment]
> 建议在顶部导航插入一个外链

已添加

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
