### ISSUE TITLE
totoro & home

### ISSUE THREAD

**Issue by skytotwo** [volfclub/travellings#623]
## 网站名称
totoro & home

## 网站网址
https://totoro.site/

## 徽标位置
侧栏

## 推荐理由
圈子共享，结交好友

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
