### ISSUE TITLE
怀春皓的站

### ISSUE THREAD

**Issue by BiliCompass** [volfclub/travellings#624]
## 网站名称
怀春皓的站

## 网站网址
https:/imbq.cn

## 徽标位置
侧栏+底部

## 推荐理由
一个学生，计算机爱好者

**Comment by volfclub** [comment]
![图片](https://user-images.githubusercontent.com/47265026/129446267-8836a2c2-0aca-46b0-a546-2b916cd65855.png)
网站挂了，抢救下吧

**Comment by BiliCompass** [comment]
> ![图片](https://user-images.githubusercontent.com/47265026/129446267-8836a2c2-0aca-46b0-a546-2b916cd65855.png)
> 网站挂了，抢救下吧

emm，好吧，最近网站在升级服务器。很快会好，到时候我重新提出一个Issue

**Comment by volfclub** [comment]
好的，这个先关闭了
