### ISSUE TITLE
Sakitami的集装箱

### ISSUE THREAD

**Issue by Sakitami** [volfclub/travellings#627]
## 网站名称
Sakitami的集装箱

## 网站网址
（💡 必须是 https 网站）
https://blog.skihome.xyz

## 徽标位置
（💡 只放在“网页底部”，或只放在“默认收起的菜单里”，审核通过率较低；
核心要求是放在 PC 打开网页后能**直接看到的地方**——一般而言，顶栏或固定的侧栏是不错的选择，具体示例可参见 Readme 或已收录的网站）
侧栏 默认展开

## 推荐理由
（💡 不会展示在 Readme）
是 个人博客哦，平时会写一些踩坑记录、过程分享、随笔什么的，希望能交到更多朋友

**Comment by volfclub** [comment]
已收录
