### ISSUE TITLE
solar’blog申请加入Travelling

### ISSUE THREAD

**Issue by denni135** [volfclub/travellings#63]
## 网站名称
solar'blog
## 网站链接
https://www.solarme,vip
## 徽标位置
右侧边栏
## 推荐理由
爱音乐，爱生活。

**Comment by volfclub** [comment]
travelling的位置是否可以再靠上一些呢（打开网站能直接看见就行）？
顺便一提，网址逗号乱入了。

**Comment by denni135** [comment]
已修改。
逗号还真没注意到，哈哈。

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
