### ISSUE TITLE
小理的小窝

### ISSUE THREAD

**Issue by lizhijunya** [volfclub/travellings#636]
## 网站名称
小理的小窝

## 网站网址
https://www.xiaolii.com

## 徽标位置
首页公告栏底部

## 推荐理由
分享生活的乐趣

**Comment by linlinzzo** [comment]
Firefox显示网站无法连接哦。
![Screenshot_20210810-185606](https://user-images.githubusercontent.com/79007796/128855067-4ca9b371-cdf7-4e5b-bf90-49564e219e94.jpg)

**Comment by lizhijunya** [comment]
那用chrome看看？我这边是正常的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月10日(周二) 晚上6:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [volfclub/travellings] 小理的小窝 (#636)




 
Firefox显示网站无法连接哦。

**Comment by lizhijunya** [comment]
等等 我发现问题了 请更改为https://xiaolii.com 
忘记了，加了www

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
没有看到开往链接？

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by lizhijunya** [comment]
好的 已经添加 顺便说一下本博客名称改为 Xiaolii's Blog，感谢！
