### ISSUE TITLE
SpinTouch's Something 申请收录

### ISSUE THREAD

**Issue by SpinTouch** [volfclub/travellings#64]
## 网站名称 
SpinTouch's Something
## 网站链接
https://spblog.tk/
## 徽标位置
网站右侧小工具栏
## 推荐理由
个人博客，分享有关任天堂DS系列的技术项目和想法

**Comment by volfclub** [comment]
travelling的位置是否可以再靠上一些呢（打开网站能直接看见就行）？

**Comment by SpinTouch** [comment]
> travelling的位置是否可以再靠上一些呢（打开网站能直接看见就行）？

已经更改了Travelling的位置，可再次看看

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
