### ISSUE TITLE
此处写你“网站的名字”

### ISSUE THREAD

**Issue by zerofrequency** [volfclub/travellings#644]
## 网站名称
zero建筑天地

## 网站网址

https://www.zefanlong.cn/
## 徽标位置
顶栏
## 推荐理由
分享生活

**Comment by linlinzzo** [comment]
检查一下SSL证书和图片，Firefox显示不安全连接。

**Comment by linlinzzo** [comment]
WordPress里面的站点地址和WordPress地址都要改为https的。

**Comment by zerofrequency** [comment]
你好请问具体是什么地方显示不安全，我这里一切正常。使用的https

从 Windows 版邮件发送

发件人: linlinzzo(林林)
发送时间: 2021年8月10日 18:36
收件人: volfclub/travellings
抄送: zerofrequency; Author
主题: Re: [volfclub/travellings] 此处写你“网站的名字” (#644)

检查一下SSL证书和图片，Firefox显示不安全连接。
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by linlinzzo** [comment]
> 你好请问具体是什么地方显示不安全，我这里一切正常。使用的https 从 Windows 版邮件发送 发件人: linlinzzo(林林) 发送时间: 2021年8月10日 18:36 收件人: volfclub/travellings 抄送: zerofrequency; Author 主题: Re: [volfclub/travellings] 此处写你“网站的名字” (#644) 检查一下SSL证书和图片，Firefox显示不安全连接。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Firefox打开你的网站，锁上有一个斜杠，显示不安全连接。

**Comment by linlinzzo** [comment]
是引用的资源造成的。myssl上面你的网站评级为B哦。请检查你的网站在引用资源的时候有没有都使用https

**Comment by linlinzzo** [comment]
你那里编辑一下issue，或者再提个issue申请修改。
