### ISSUE TITLE
第300号【zebwq.top】链接更改

### ISSUE THREAD

**Issue by MinecraftMEMZ** [volfclub/travellings#654]
## 问题描述
我是第300号网站（https://zebwq.top)的站长，现在已经将网站变更为https://imfurry.com，请管理员帮忙更改。
## 标记位置
travelling标记在网站公告中，一打开就能看到。

**Comment by volfclub** [comment]
好的，请顺便看下 readme 更新下资源

**Comment by MinecraftMEMZ** [comment]
好嘞，谢谢你~

**Comment by HowieHz** [comment]
link #515
