### ISSUE TITLE
王荣胜博客申请收录

### ISSUE THREAD

**Issue by WangRongsheng** [volfclub/travellings#66]
## 网站名称
王荣胜
## 网站链接
https://sqdxwz.com/
## 徽标位置
网站底部
## 推荐理由
个人知识分享

**Comment by volfclub** [comment]
可否顶部导航放个外链

**Comment by WangRongsheng** [comment]
> 可否顶部导航放个外链

您好，已调整到显眼位置

**Comment by volfclub** [comment]
建议参考下已收录的网站，再导航处放个外链吧。
现在插得位置太影响你的博客了。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
