### ISSUE TITLE
刀客收录申请

### ISSUE THREAD

**Issue by terrenceftz** [volfclub/travellings#67]
网站名称：刀客
网址：https://blog.mboker.cn
联系邮箱：admin@mboker.cn

**Comment by volfclub** [comment]
建议在网页直接能看到的地方放个外链，如顶部导航

**Comment by terrenceftz** [comment]
> 建议在网页直接能看到的地方放个外链，如顶部导航

收到，因为顶部导航设置较多，我改下申请信息，修改为博客引导页，同时也会在博客内部保留该底部链接。
网站名称：刀客
网址：https://mboker.cn
联系邮箱：admin@mboker.cn

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
