### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by WhitemuTeam** [volfclub/travellings#670]
# 建议（三者取其一）：
1. 更新 无缝接力β 中的`travelling.min.js`
2. 停止对 无缝接力β  中的`travelling.min.js`的更新支持
3. 或更改`travelling.min.js`源码，使其在被使用时能够跳转至`travellings.links`

以上的目的是为了某些懒人不更新博客js而造成我们在尝试使用开往“开往”下一个站点的时候出现无法访问下一站点的问题

**Comment by volfclub** [comment]
无缝接力β 已标明不推荐了，这个 min.js 实际上是由 jsdeliver 根据 release 自动生成的，理应是最新版本，若不指定版本号的话。但不知到啥，实际更新的并不理想。后续删掉算了。
