### ISSUE TITLE
UtopiaXC‘s Sites

### ISSUE THREAD

**Issue by UtopiaXC** [volfclub/travellings#675]
## 网站名称  
UtopiaXC‘s Sites

## 网站网址  
https://www.utopiaxc.cn/

## 徽标位置  
页面顶部（标题下方）

## 推荐理由  
这个网站是我的站点导航站，里面包含了我的博客，书站，开源项目等等一系列的网站。我对这个开往这个项目心水很久了，但是之前我的网站结构太杂乱了，今天稍微魔改了个导航站出来，希望和大家一起交流技术和生活

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
