### ISSUE TITLE
小丁的博客

### ISSUE THREAD

**Issue by xdingya** [volfclub/travellings#677]
## 网站名称
小丁的博客

## 网站网址
https://xding.top/

## 徽标位置
顶栏

## 推荐理由
没想到【开往】还得申请我还以为我自动记录站点信息(白给2个月)（阿巴阿巴阿巴）
个人技术、生活分享博客，记录点点滴滴！

**Comment by volfclub** [comment]
亲，请看下readme，不要在用纸飞机图标了

**Comment by xdingya** [comment]
> 亲，请看下readme，不要在用纸飞机图标了
已修改！
