### ISSUE TITLE
小岚的小窝

### ISSUE THREAD

**Issue by mcxiaolan** [volfclub/travellings#678]
## 网站名称
小岚的小窝

## 网站网址
https://blog.mcxiaolan.top

## 徽标位置
菜单

## 推荐理由
分享交流

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
