### ISSUE TITLE
点滴生活申请收录

### ISSUE THREAD

**Issue by gz83** [volfclub/travellings#68]
网站名称:点滴生活

网站链接:https://www.gdgzyfqh.club/

徽标位置:页面右侧

推荐理由:自己做的博客站,希望多点人访问.

**Comment by volfclub** [comment]
您的文章似乎有些少，建议 8 篇文章后再来申请试试看？

**Comment by gz83** [comment]
> 您的文章似乎有些少，建议 8 篇文章后再来申请试试看？

好的

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
