### ISSUE TITLE
此处写你“网站的名字”

### ISSUE THREAD

**Issue by BambooMC** [volfclub/travellings#681]
## 网站名称
竹MC的博客

## 网站网址
https://bamboomc.cn

## 徽标位置
顶部导航栏和页尾

## 推荐理由
分享游戏干货

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
没有看到随机码，电话联系无法接通。开往成员权益审核驳回。

**Comment by BambooMC** [comment]
> 没有看到随机码，电话联系无法接通。开往成员权益审核驳回。

抱歉，上午没能在github找到这条issue，随机码是QGOLtH8lrP，电话上填错了，麻烦了

**Comment by BambooMC** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            抱歉，上午没能在github找到这条issue，电话上填错了，重新填了一份，随机码是QGOLtH8lrP，麻烦了
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年1月12日 15:09
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [travellings-link/travellings] 此处写你“网站的名字” (#681)
        
      
    
  
  

没有看到随机码，电话联系无法接通。开往成员权益审核驳回。

**Comment by linlinzzo** [comment]
已将信息移交给FarCDN，等待CDN方面的处理。

**Comment by BambooMC** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，再次感谢
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年1月13日 08:45
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [travellings-link/travellings] 此处写你“网站的名字” (#681)
        
      
    
  
  

已将信息移交给FarCDN，等待CDN方面的处理。
