### ISSUE TITLE
wrs博客收录

### ISSUE THREAD

**Issue by WangRongsheng** [volfclub/travellings#69]
## 网站名称
王荣胜
## 网站链接
https://sqdxwz.top
## 徽标位置
顶部
## 推荐理由
计算机学科的渣渣

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
