### ISSUE TITLE
自说自话

### ISSUE THREAD

**Issue by Kagurain** [volfclub/travellings#70]
## 网站名称

**自说自话**

## 网站链接

**https://rua.ink**

## 徽标位置

**全站左侧菜单栏**

## 推荐理由

**优质技术博客**

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
