### ISSUE TITLE
摸鱼堂申请收录

### ISSUE THREAD

**Issue by moefishtang** [volfclub/travellings#71]
## 网站名称
**摸鱼堂-来摸鱼哦**
## 网站链接
**https://moefishtang.lingdi.uk/**
## 徽标位置
**首页右侧工具栏，网页底部，网页顶栏，友情链接页面**
## 推荐理由
**分享折腾wordpress的经历,很喜欢这个项目**

**Comment by moefishtang** [comment]
顶栏也加上travelling的链接了

**Comment by volfclub** [comment]
你的网站国内访问速度太买了，优化下试试？
http://www.17ce.com/site/http/20200409_f1f223107a0e11eaa781732777d644c9:1.html

**Comment by moefishtang** [comment]
> 你的网站国内访问速度太买了，优化下试试？
> http://www.17ce.com/site/http/20200409_f1f223107a0e11eaa781732777d644c9:1.html

您好！
我已经对我的网页做了一些优化，现在访问速度应该可以了，能再试试吗？谢谢。

**Comment by volfclub** [comment]
已收录，网址为 https://moefishtang.xyz/

**Comment by moefishtang** [comment]
您好，我换域名了，能把域名改成https://moefishtang.xyz/ 吗，谢谢（原域名已设置301跳转）

**Comment by volfclub** [comment]
需要移除你的网站吗？

> Hey guys:
I'm sorry that I had to stop my blog. 
Beacuse I had to spend my time on my study.
Please remove my blog from your blogroll,thanks.
yours
moefishtang

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
