### ISSUE TITLE
遇见孤独申请收录

### ISSUE THREAD

**Issue by YueeGee** [volfclub/travellings#72]
## 网站名称
遇见孤独

## 网站链接
https://blog.aenjoy.cn/

## 徽标位置
顶部导航栏和底部

## 推荐理由
优质个人生活/技术博客

**Comment by volfclub** [comment]
建议将顶部的彩蛋直接改为开放，便于直接看到

**Comment by YueeGee** [comment]
底部也添加上了a标签

**Comment by YueeGee** [comment]
> 建议将顶部的彩蛋直接替换开放，以便直接看到

底部也添加上了a标签

**Comment by YueeGee** [comment]
> 建议将顶部的彩蛋直接替换开放，以便直接看到

首页导航栏处已将“彩蛋”改为“开往”  同时底部站点标题处也添加a标签链接了

**Comment by YueeGee** [comment]
顶部导航栏和页脚已增加徽标。

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
