### ISSUE TITLE
涅槃博客

### ISSUE THREAD

**Issue by love2wind** [volfclub/travellings#742]
## 网站名称

涅槃博客

## 网站网址

 https://love2wind.cn

## 徽标位置

网站侧边栏

## 内容方向

 一个专注分享国内外各种资源的平台，日常分享网络上搜集的各种资源、图片、视频、音乐、工具、软件、APP、网站、电子书的个人博客

**Comment by volfclub** [comment]
已收录

**Comment by love2wind** [comment]
网站迁移至https://niepan.org，请修改。

**Comment by Big-Cake-jpg** [comment]
> 网站迁移至https://niepan.org，请修改。

为方便修改，还请您重新提交一个 Issue 申请变更……

**Comment by love2wind** [comment]
> > 网站迁移至[https://niepan.org，请修改。](https://niepan.org%EF%BC%8C%E8%AF%B7%E4%BF%AE%E6%94%B9%E3%80%82)
> 
> 为方便修改，还请您重新提交一个 Issue 申请变更……

已提交
