### ISSUE TITLE
秋季问题站点报告

### ISSUE THREAD

**Issue by Moemu** [volfclub/travellings#745]
# 问题站点
1. 站点: https://ccccc.cyou/ 序号: 171 原因: 域名不存在
2. 站点: www.wenchong.space 序号: 339 原因：未备案 注: 该用户目前使用 http://coolchong.cn/ 作为博客，其已放置开往友链
3. 站点: https://chuxjian.asia/ 序号: 362 原因：无法访问此网站（域名停靠dnspod)
4. 站点: www.zk1220.com 序号 137 原因 502
# 一个小建议
如果不麻烦的话，烦请将[readme.md的第18行](https://github.com/volfclub/travellings/blob/master/README.md?plain=1#L18)中的`[WhitemuTeam](https://github.com/WhitemuTeam)`改为`[@Moemu](https://github.com/Moe) `不然会显得很突兀
2022.1.29更新: 源WhitemuTeam->Moemu

**Comment by linlinzzo** [comment]
第一和第三个网站反应的问题已处理，第四个目前正常。
