### ISSUE TITLE
申请恢复 SpinTouch's Sth. https://spinaround.tk/

### ISSUE THREAD

**Issue by SpinTouch** [volfclub/travellings#749]
之前因为网站迁移漏了开往的图案，先已恢复。
另外网站迁移新域名：https://spinaround.tk/ 。

**Comment by linlinzzo** [comment]
已重新添加到列表，并更换网站信息。序号：52

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已移除开往链接，现已将您移除，如需加入开往，可再次按照流程申请。 @SpinTouch
