### ISSUE TITLE
蝶恋花申请收录

### ISSUE THREAD

**Issue by KylinLee** [volfclub/travellings#75]
## 网站名称
蝶恋花

## 链接
http://liqilinhub.cloud/friends.html

## 徽标位置
友链主要内容第一个位置

## 推荐理由
保持持续更新

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
