### ISSUE TITLE
老哲的小客栈

### ISSUE THREAD

**Issue by Masle1** [volfclub/travellings#750]
## 网站名称
老哲的小客栈

## 网站网址
https://masle.top

## 徽标位置
默认收起的侧边栏中，火车图标

## 内容方向
主要记录一些学习笔记以及一些有趣的事情。
站点的名称叫“小客栈”，意思主要是我认为这个网站是我的避风港。也欢迎大家能在我的客栈里收获到些许快乐。

**Comment by volfclub** [comment]
内容有些少，要不在写写？

**Comment by Masle1** [comment]
> 内容有些少，要不在写写？

Ok，主要是不想凑数量。文章会慢慢发布。
如果你觉得数量足够了，麻烦收录一下哈

**Comment by linlinzzo** [comment]
你用的是云游君的模板吗？我现在添加一下。

**Comment by linlinzzo** [comment]
已添加
