### ISSUE TITLE
雾时之森

### ISSUE THREAD

**Issue by Fog-Forest** [volfclub/travellings#755]
## 网站名称
雾时之森

## 网站网址
https://fairysen.com/

## 徽标位置
顶栏&移动端测栏

## 内容方向
分享一些建站运维技巧和一些实用脚本，分享自己的折腾记录和成果，记录生活。

**Comment by volfclub** [comment]
你好，没有找到放置开往链接的位置

**Comment by Fog-Forest** [comment]
移动端在侧边栏，PC在顶栏最后一个

**Comment by volfclub** [comment]
已收录
