### ISSUE TITLE
煎茶

### ISSUE THREAD

**Issue by songtianlun** [volfclub/travellings#756]
## 网站名称

煎茶

## 网站网址

https://www.frytea.com

## 徽标位置

顶栏

## 内容方向

原创，优质、有深度、有思考的内容分享，技术、复盘、生活。

**Comment by volfclub** [comment]
已收录

**Comment by Allenyou1126** [comment]
尊敬的站长您好，我们接到反馈，您的站点访问时返回 404 错误码。我们已经将您的站点状态置为 ERROR，并暂停了到您的站点的跳转。

我们希望您可以排查相关问题，并在 14 天内在该 Issue 下方回复。

感谢您对开往的支持。

**Comment by songtianlun** [comment]
> 尊敬的站长您好，我们接到反馈，您的站点访问时返回 404 错误码。我们已经将您的站点状态置为 ERROR，并暂停了到您的站点的跳转。
> 
> 我们希望您可以排查相关问题，并在 14 天内在该 Issue 下方回复。
> 
> 感谢您对开往的支持。

抱歉，出现一个配置错误，已经修复，现在正常访问了。

**Comment by Allenyou1126** [comment]
已知悉，我们已经恢复了到您的站点的正常跳转。感谢您对开往的支持。
