### ISSUE TITLE
LifeAlsoIsGG's blog

### ISSUE THREAD

**Issue by LifeAlsoIsGG** [volfclub/travellings#76]

**Comment by volfclub** [comment]
建议在打开网页后能直接看到的地方放一个外链，如顶部导航

**Comment by LifeAlsoIsGG** [comment]
行吧，但是最近有点忙可能没时间，到时候加上去，先把我加入吧，怕到时候忘了谢谢

**Comment by LifeAlsoIsGG** [comment]
你好，我已经加上了，拉我上车吧，谢谢啦

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
