### ISSUE TITLE
windsky博客申请收录

### ISSUE THREAD

**Issue by YanLiye2003** [volfclub/travellings#77]
## 网站名称
Windsky博客
## 网站链接
https://www.okace.cn
## 徽标位置
首页，页脚
## 推荐理由
觉得挺好的

**Comment by volfclub** [comment]
建议在打开网页后能直接看到的地方放一个外链，如顶部导航

**Comment by YanLiye2003** [comment]
已修改完成

**Comment by volfclub** [comment]
建议参考下这个，让访客直接看到 https://blog.aenjoy.cn/
