### ISSUE TITLE
Java基础知识库

### ISSUE THREAD

**Issue by zkeq** [volfclub/travellings#777]
## 网站名称
> - Java 基础知识库

## 网站网址
> - https://javadocs.zkeq.xyz

## 徽标位置
> - 顶部

## 内容方向
> - Java 基础知识库, 初学者可以将本网站做docs使用,
> - 已经掌握后还有实战案例可以练习
> - 本站与 https://icodeq.com  相补充

**Comment by volfclub** [comment]
已收录

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/c3864e38-420e-41e6-8870-2c97fff2f9fa)

![Image](https://github.com/user-attachments/assets/ba3b168d-24a5-4c26-91cc-c7afa8a84d44)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
