### ISSUE TITLE
白鸽小屋

### ISSUE THREAD

**Issue by baige007** [volfclub/travellings#789]
## 网站名称
白鸽小屋

## 网站网址
https://www.sccens.net/

## 徽标位置
侧边栏；

## 内容方向
搭建‘白鸽小屋’主要记录一下日常生活和学习笔记。隔着山海，我们互不相识，却盯着同一片晚霞，做着同一件事情。

**Comment by linlinzzo** [comment]
让你久等了，等会添加。

**Comment by linlinzzo** [comment]
已添加。
