### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by L-20021213** [volfclub/travellings#79]
## 网站名称
Smilear's Blog
## 网站链接
http://smilear.cn/
## 徽标位置
侧栏
## 推荐理由
个人博客分享生活

**Comment by volfclub** [comment]
建议在打开网页后能直接看到的地方放一个外链，如侧栏导航

**Comment by volfclub** [comment]
网站显示未备案

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
