### ISSUE TITLE
请求更新站点信息

### ISSUE THREAD

**Issue by icedtangerine7** [volfclub/travellings#795]
序号：392
名称：冰橘の小窝
网站地址：https://blog.moe233.net

使用 cdn 了，由于原来的裸域名无法设置 CNAME 解析所以不得不换成二级域名了......  
给您添麻烦了，对不起╥﹏╥...

**Comment by linlinzzo** [comment]
现在还要吗？我可以帮忙添加到pull request中。

**Comment by icedtangerine7** [comment]
> 现在还要吗？我可以帮忙添加到pull request中。

好的，麻烦了

**Comment by linlinzzo** [comment]
已更新。
