### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by uniartisan** [volfclub/travellings#8]
## 网站名称
致远博客
## 网站链接
https://blog.uniartisan.com/
## 徽标位置
全局左侧导航栏友情链接，左下角版权信息旁
## 推荐理由
本科在读，个人开发者。

**Comment by volfclub** [comment]
已收录，
建议放在直接可以看到的地方

**Comment by uniartisan** [comment]
> 已收录，
> 建议放在直接可以看到的地方

修正后左下角全局可见，毋须满足屏幕宽度>=1000。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
