### ISSUE TITLE
6zgm 申请加入

### ISSUE THREAD

**Issue by California3** [volfclub/travellings#80]
## 网站名称
艺术长廊
## 网站链接
https://www.6zgm.com
## 徽标位置
侧边栏
## 推荐理由
一场艺术文化体验

**Comment by volfclub** [comment]
请问你的网站如此多的媒体资源，是否可以较长时间的运行下去？

**Comment by California3** [comment]
可以，这个维护后期成本很低，只要服务器不挂即可，自己设计的框架，有足够的缓存，使用Redis缓存缓解一些压力。资源方面不必担心，已经有稳定的代码配套。

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
