### ISSUE TITLE
[修改] LCZBlog

### ISSUE THREAD

**Issue by LiCaoZ** [volfclub/travellings#805]
# 博客信息更新 / 域名更换

## 网站序号

232

## 域名更换

原域名 blog.shiertx.com 新域名 licaoz.com

已设置重定向

### 网站名称

原名称 十二博客 新名称 LCZBlog

### 徽标位置

底部 footer

**Comment by linlinzzo** [comment]
网站编号？

**Comment by LiCaoZ** [comment]
> 网站编号？

已更新

**Comment by linlinzzo** [comment]
已在我的pr中修改。
