### ISSUE TITLE
周海棠啦 申请收录

### ISSUE THREAD

**Issue by Wygdbb** [volfclub/travellings#82]
## 网站名称
周海棠啦
## 网站链接
https://www.wygdbb.com
## 徽标位置
底部
## 推荐理由
喜欢Linux，爱折腾~

**Comment by volfclub** [comment]
建议在打开网页后能直接看到的地方放一个外链，如顶部导航

**Comment by Wygdbb** [comment]
> 建议在打开网页后能直接看到的地方放一个外链，如顶部导航

好的，最近主题换默认的了  尽快安排上！

**Comment by volfclub** [comment]
目前还没看到顶部有链接，改好后记得回复下
