### ISSUE TITLE
Lanta Blog

### ISSUE THREAD

**Issue by RealLanta** [volfclub/travellings#832]
## 网站名称
> Lanta Zone
## 网站网址
> https://www.lanta.cyou
## 徽标位置
> 网页底部
## 内容方向
> 分享Linux知识和生活日常为主

**Comment by linlinzzo** [comment]
啊哈，云游君的模板。等会处理。

**Comment by linlinzzo** [comment]
已添加。

**Comment by RealLanta** [comment]
多谢处理
