### ISSUE TITLE
.link链接很卡，经常连接超时 请在标题这写“网站名称”

### ISSUE THREAD

**Issue by Lanky6** [volfclub/travellings#840]
## 网站名称
> - 💡 会在 Readme 中展示；

## 网站网址
> - 💡 必须是 http**s** 网站；
> - 💡 `bar, best, cloud, digital, guru, life, live, miami, online, rest, shop, site, store, surf, today, website, world, sapce, fun` 这些域名往往购买时便宜，但第二年续费会在 100 元以上，你会坚持用这个域名吗？如果你更新了域名，记得打开 issues 更新信息。

## 徽标位置
> - 💡 只放在“网页底部”，或只放在“默认收起的菜单里”，审核通过率较低。请放在打开网页后能**直接看到的地方**（顶栏或固定的侧栏是不错的选择，可参见 Readme 或已收录的网站）；

## 内容方向
> - 💡 不会展示在 Readme ；
> - 💡 你想与网络世界分享什么？

> 【填写时请删除带有 💡 的提示内容行（包括这句）】

**Comment by linlinzzo** [comment]
有镜像可供选择。
