### ISSUE TITLE
昏暗槐花的咸鱼小店申请收录

### ISSUE THREAD

**Issue by HAHH9527** [volfclub/travellings#85]
## 网站名称
昏暗槐花的咸鱼小店
## 网站链接
https://hahh9527.github.io/
## 徽标位置
侧栏/友链页面
## 推荐理由
原创工具/个人生活记录

**Comment by volfclub** [comment]
网站内容有些少，建议8篇以上后再来申请一次。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
