### ISSUE TITLE
开往域名使用的cdn服务疑似被墙，域名打不开

### ISSUE THREAD

**Issue by Lanky6** [volfclub/travellings#856]
开往域名使用的cdn服务疑似被墙，域名打不开。
还有网站收录很慢，没人维护，建议建立QQ群并且邀请可靠的其他人一起在网站上维护

**Comment by qystudio0** [comment]
同意，可以招募志愿者维护项目

**Comment by linlinzzo** [comment]
我会不定期将网站信息的修改添加到pr中，等owner通过。

**Comment by qystudio0** [comment]
但是还是建议招收更多维护者更方便

**Comment by linlinzzo** [comment]
> 但是还是建议招收更多维护者更方便

我刚刚已经去提醒维护者了，明天我也会帮忙处理一下。
