### ISSUE TITLE
Ma's Blog 申请收录

### ISSUE THREAD

**Issue by 3184876** [volfclub/travellings#87]
## 网站名称
Ma's Blog
## 网站链接
https://6773.ink
## 徽标位置
博客底部右侧信息（左侧栏有超链接位置）
## 推荐理由
努力做到周更三次左右

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
