### ISSUE TITLE
Smilear's Blog申请收录

### ISSUE THREAD

**Issue by L-20021213** [volfclub/travellings#88]
## 网站名称
Smilear's Blog
## 网站链接
http://smilear.cn/
## 徽标位置
导航栏
## 推荐理由
个人博客，想让更多人看到

**Comment by volfclub** [comment]
网站打不开 😥

> 导致网站被拦截的原因可能如下：
原因一：该网站已备案，但尚未提交白名单，登录服务提供商控制台-备案管理处提交白名单后即可正常访问；
原因二：根据工信部相关法规，该网站尚未进行备案，请登录服务提供商控制台-备案管理处提交备案；
本页面为默认提示页面，如网站存在以上问题，可联系服务提供商处理。
谢谢合作！

**Comment by volfclub** [comment]
现在可以访问了，但您的网站没有 上https
