### ISSUE TITLE
狼堡实验室

### ISSUE THREAD

**Issue by Qxin-X** [volfclub/travellings#885]
## 网站名称
狼堡实验室

## 网站网址
https://blog.xieqingxin.com

## 徽标位置
顶栏 和 底部

## 内容方向
一个专注于互联网 WEBAPP 领域的博客

**Comment by linlinzzo** [comment]
等会处理。

**Comment by linlinzzo** [comment]
已添加。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
