### ISSUE TITLE
Moechu 申请收录

### ISSUE THREAD

**Issue by Andrew8102** [volfclub/travellings#89]
## 网站名称
萌豚 Moechu
## 网站链接
https://moechu.cn
## 徽标位置
顶部、底部
## 推荐理由
认为这非常符合初代互联网的共享的品质

**Comment by volfclub** [comment]
已收录

**Comment by Andrew8102** [comment]
已经完成修改，辛苦了

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by Andrew8102** [comment]
感谢提醒，tg验证码发了两个，手残点错了，被管理员封禁，有无解封方法？@linlinzzo
