### ISSUE TITLE
Kouki-α

### ISSUE THREAD

**Issue by koukihk** [volfclub/travellings#890]
## 网站名称
Kouki-α

## 网站网址
https://kouki.ltd/

## 徽标位置
侧边栏+底部+导航栏

## 内容方向
笔记&心得&作业&随笔

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
