### ISSUE TITLE
yunyuyuan's blog

### ISSUE THREAD

**Issue by yunyuyuan** [volfclub/travellings#892]
## 网站名称
yunyuyuan's blog

## 网站网址
https://blog.halberd.cn

## 徽标位置
顶部

## 内容方向
技术，记录，书籍

**Comment by yunyuyuan** [comment]
不维护了吗

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
