### ISSUE TITLE
我爱IT ❤ 网络安全

### ISSUE THREAD

**Issue by 9201314** [volfclub/travellings#896]
## 网站名称
我爱IT ❤ 网络安全

## 网站网址
https://b.woai.it/

## 徽标位置
网页底部

## 内容方向
个人博客

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
