### ISSUE TITLE
申请收录静静的小窝

### ISSUE THREAD

**Issue by wznmickey** [volfclub/travellings#90]
## 网站名称
静静的小窝
## 网站链接
https://wznmickey.com
## 徽标位置
侧边栏&友链页面
## 推荐理由
记录自己的感受与收获

**Comment by volfclub** [comment]
你的网站在国内访问速度很慢，可能是Couldflare减速的原因，优化下试试？
http://www.17ce.com/site/http/20200417_69ca50d0807f11ea82f00f72e195befa:1.html

建议静态资源可用 jsdelivr 加速

**Comment by wznmickey** [comment]
> 你的网站在国内访问速度很慢，可能是Couldflare减速的原因，优化下试试？
> http://www.17ce.com/site/http/20200417_69ca50d0807f11ea82f00f72e195befa:1.html
> 
> 建议静态资源可用 jsdelivr 加速

之前有些改动，缓存会出问题所以关掉了，现在已经开了。
图片用的都是图床，现在打开的平均速度3.127s，不知道有什么要求？
谢谢。

**Comment by volfclub** [comment]
我这边是联通宽带，加载1分钟以上看不见内容 https://sm.ms/image/E25zQgti1xDvWlh
网站检测显示国内很多节点是异常的 http://www.17ce.com/site/http/20200417_27eaa1d0808711ea99f98927441aa9a5:1.html

**Comment by wznmickey** [comment]
http://www.17ce.com/site/http/20200418_81b0d1a0817f11ea99f98927441aa9a5:1.html
我用百度试的时候也有许多没连上的，可能不是我这边的问题

**Comment by wznmickey** [comment]
> 我这边是联通宽带，加载1分钟以上看不见内容 https://sm.ms/image/E25zQgti1xDvWlh
> 网站检测显示国内很: 节点是异常的 http://www.17ce.com/site/http/20200417_27eaa1d0808711ea99f98927441aa9a5:1.html
http://www.17ce.com/site/http/20200418_81b0d1a0817f11ea99f98927441aa9a5:1.html
我用百度试的时候也有许多没连上的，可能不是我这边的问题

**Comment by volfclub** [comment]
目前文本主体正常加载了，但这张头像加载不出来
https://s2.ax1x.com/2019/04/27/EuyEUP.png

已收录

**Comment by qystudio0** [comment]
可能是早期有站点异常，现在重新加入

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by wznmickey** [comment]
自动回复：已收到，谢谢。
