### ISSUE TITLE
ポ叶 - shutiaoya

### ISSUE THREAD

**Issue by chengcff** [volfclub/travellings#902]
## 网站名称
ポ叶 - shutiaoya

## 网站网址
https://www.shutiaoya.com/

## 徽标位置
顶栏中间和左侧栏

## 内容方向
技术开发，教程，资源

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/2ee94fd8-c946-4928-9483-1ac06a9c5850)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
