### ISSUE TITLE
“张赛东的艺苑”

### ISSUE THREAD

**Issue by adong666666** [volfclub/travellings#903]
## 网站名称
> - 💡 张赛东的艺苑；

## 网站网址
> - 💡 https://zsd.name/；

## 徽标位置
> - 💡顶栏；

## 内容方向
> - 💡 计算机技术；
> - 💡 数据结构与算法；
> - 💡 移动开发；
> - 💡 个人生活与爱好；

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
