### ISSUE TITLE
y7n05h 的技术分享 域名变动

### ISSUE THREAD

**Issue by Y7n05h** [volfclub/travellings#907]
原网站 https://blog.y7n05h.xyz 现已迁移至 https://blog.y7n05h.dev

**Comment by linlinzzo** [comment]
能提供一下网站序号吗？就是列表前面的序号。

**Comment by Y7n05h** [comment]
> 能提供一下网站序号吗？就是列表前面的序号。

359

**Comment by linlinzzo** [comment]
已修改。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by Y7n05h** [comment]
> 请您及时更换相关地址，谢谢配合。

已完成更换，感谢提醒。
