### ISSUE TITLE
| 387 | 网站修改信息

### ISSUE THREAD

**Issue by guangsudalao** [volfclub/travellings#909]
原来的域名已经弃用
把原来的| 387 | 顶栏 | 光速大佬的窝 | https://blog.guangsudalao.top 
修改成 Guangsudalao's blog https://blog.dlya.top 
387号
谢谢啦

**Comment by linlinzzo** [comment]
已在我的pr中修改。

**Comment by linlinzzo** [comment]
pr已经被合并，请关闭issue
