### ISSUE TITLE
申请收录xiadengmaのblog

### ISSUE THREAD

**Issue by XIADENGMA** [volfclub/travellings#91]

**Comment by volfclub** [comment]
建议顶部也放置一个外链，打开网页后可以直接看到

**Comment by XIADENGMA** [comment]
好的

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
