### ISSUE TITLE
ncc的个人网站申请收录

### ISSUE THREAD

**Issue by fghwett** [volfclub/travellings#92]
## 网站名称
ncc的个人网站
## 网站链接
https://www.zqcnc.cn
## 徽标位置
侧栏
## 推荐理由
两年博客，分享自己的生活经验和收藏列表，希望能帮助更多人发现优质内容。

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by fghwett** [comment]
好的 我将尽快更换
