### ISSUE TITLE
Diego申请加入

### ISSUE THREAD

**Issue by diego3893** [volfclub/travellings#93]
## 网站名称 
Diego's Blog

## 网站链接 
http://blog.diego.plus:5800

## 徽标位置 
侧栏

## 推荐理由 
这是一个很好的项目，想自己的见闻被跟多人看见

**Comment by volfclub** [comment]
已经收录过diego这个域名了

**Comment by diego3893** [comment]
您好，这个是我的另一个网站，这个才是主站，可以把以前那个删掉，谢谢



---原始邮件---
发件人: "逊狼"<notifications@github.com&gt;
发送时间: 2020年4月17日(周五) 下午4:04
收件人: "volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"diego3893"<diegozcx@foxmail.com&gt;;
主题: Re: [volfclub/travellings] Diego申请加入 (#93)




 
已经收录过diego这个域名了

**Comment by volfclub** [comment]
网址后面一定要跟着端口吗？

**Comment by diego3893** [comment]
嗯嗯，我的nas80端口不能用



---原始邮件---
发件人: "逊狼"<notifications@github.com&gt;
发送时间: 2020年4月20日(周一) 上午10:54
收件人: "volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"diego3893"<diegozcx@foxmail.com&gt;;
主题: Re: [volfclub/travellings] Diego申请加入 (#93)




 
网址后面一定要跟着端口吗？

**Comment by volfclub** [comment]
我不太了解NAS，问了下朋友应该是没备案造成的。
给你通过了，如果网址更换了，记得回来说下。
顺便一说，可以试试ZEIT加静态博客，可能会省心些。

**Comment by diego3893** [comment]
哦哦哦，好的👌，谢谢大大！



发自我的&nbsp;iPad


------------------ 原始邮件 ------------------
发件人: 逊狼 <notifications@github.com&gt;
发送时间: 2020年4月23日 19:39
收件人: volfclub/travellings <travellings@noreply.github.com&gt;
抄送: diego3893 <diegozcx@foxmail.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[volfclub/travellings] Diego申请加入 (#93)





 
我不太了解NAS，问了下朋友应该是没备案造成的。
 给你通过了，如果网址更换了，记得回来说下。
 顺便一说，可以试试ZEIT加静态博客，可能会省心些。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
