### ISSUE TITLE
及时行乐申请收录

### ISSUE THREAD

**Issue by LenHanGod** [volfclub/travellings#94]
## 网站名称
及时行乐
## 网站链接
https://www.jsxlo.com/
## 徽标位置
顶部
## 推荐理由
希望可以将自己的点点滴滴，让更多人看见！

**Comment by volfclub** [comment]
你的网站在国内访问速度很慢，可能是Couldflare减速的原因，优化下试试？
http://www.17ce.com/site/http/20200417_a96a2b80808311ea99f98927441aa9a5:1.html

建议静态资源可用 jsdelivr 加速

**Comment by LenHanGod** [comment]
这是优化以后的效果，麻烦收录，小站点速度不够快见谅！
http://www.17ce.com/site/http/20200417_a96a2b80808311ea99f98927441aa9a5:1.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"逊狼"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 下午4:17
收件人:&nbsp;"volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送:&nbsp;"我要回幼儿园当学霸"<1464630629@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [volfclub/travellings] 及时行乐申请收录 (#94)





 
你的网站在国内访问速度很慢，可能是Couldflare减速的原因，优化下试试？
 http://www.17ce.com/site/http/20200417_a96a2b80808311ea99f98927441aa9a5:1.html
 
建议静态资源可用 jsdelivr 加速
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by LenHanGod** [comment]
这是优化以后的效果，麻烦收录，小站点速度不够快见谅！
http://www.17ce.com/site/http/20200417_a96a2b80808311ea99f98927441aa9a5:1.html

**Comment by LenHanGod** [comment]
> 您的网站在国内访问速度很慢，可能是Couldflare减速的原因，优化下试试？[http:](http://www.17ce.com/site/http/20200417_a96a2b80808311ea99f98927441aa9a5:1.html) //www.17ce.com/site/http/20200417_a96a2b80808311ea99f98927441aa9a5:1.html
> [](http://www.17ce.com/site/http/20200417_a96a2b80808311ea99f98927441aa9a5:1.html)
> 
> 建议静态资源可用jsdelivr加速

这是优化以后的效果，麻烦收录，小站点速度不够快见谅！
http://www.17ce.com/site/http/20200417_a96a2b80808311ea99f98927441aa9a5:1.html

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
