### ISSUE TITLE
iSwl申请收录

### ISSUE THREAD

**Issue by zhx6** [volfclub/travellings#95]
## 网站名称
iSwl's Blog
## 网站链接
https://blog.iswl.vip/
## 徽标位置
底部
## 推荐理由
想让更多的人知道我这个平凡的小站

**Comment by volfclub** [comment]
建议有8篇文章再来申请一次试试？

**Comment by zhx6** [comment]
> 建议有8篇文章再来申请一次试试？

再次申请，文章已经超过8篇了，还会继续努力的，希望通过下~对了顶部导航栏和底部我都有加入“开往”

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
