### ISSUE TITLE
遇见孤独申请收录

### ISSUE THREAD

**Issue by YueeGee** [volfclub/travellings#97]
## 网站名称
遇见孤独
## 网站链接
https://blog.aenjoy.cn/
## 徽标位置
首页导航栏顶部和底部
## 推荐理由
优质个人博客（逃

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
