### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by boxcheese** [volfclub/travellings#99]
## 网站名称
魏·美文网
## 网站链接
https://xiaowei.china97.cn
## 徽标位置
低栏和侧滑栏
## 推荐理由
美文了解人们的心情与感受，每日美文从写作开始！

**Comment by volfclub** [comment]
建议在侧栏导航或其他打开网页能直接看到的地方放个外链吧

**Comment by a16207** [comment]
我侧滑栏打开就可以看见一串英文，看到的人应该会不理解，或者我直接改成开往，不过我这是可以看见的侧滑栏抽屉，和低栏，。

**Comment by a16207** [comment]
因为这个要遵循语法，所以不能直接放置，请体谅，谢谢

**Comment by a16207** [comment]
![Screenshot_2020-04-17-20-42-10-217_com MyFusApp ceshi](https://user-images.githubusercontent.com/63401583/79570554-411f6580-807f-11ea-9d26-4768937a640d.png)
![Screenshot_2020-04-17-20-42-15-633_com MyFusApp ceshi](https://user-images.githubusercontent.com/63401583/79570565-467cb000-807f-11ea-81c2-35af630734ff.png)

**Comment by a16207** [comment]
> 建议在侧栏导航或其他打开网页能直接看到的地方放个外链吧

okokok

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
